### ISSUE TITLE
provide an ondisk statemachine example

### ISSUE THREAD

**Issue by xkeyideal** [lni/dragonboat#100]
this is my multi-group raft ondisk statemachine example based on dragonboat [mraft](https://github.com/xkeyideal/mraft).

Because the understanding of this framework is not deep enough, the example maybe have some faults, PTAL.

Follow-up will be used in the production environment to instead of database store datas, reduce database component dependencies and network overhead between application with database.

Write the example, has some features want to be supported by dragonboat.

1. The statemachine instance can provide to developer for initializing configure, such as data storage directory and so on. Now these configures just write by constants.
2. The Sync() function whether maybe lost in-memory datas when the program suddenly crashed before exec Sync()  or not .

**Comment by lni** [comment]
@xkeyideal examples, including the on disk example, can be found in https://github.com/lni/dragonboat-example

note that the above mentioned examples are just examples, they are _NOT_ benchmark programs as they are intentionally implemented in the most straight forward way.

**Comment by xkeyideal** [comment]
I know the dragonboat-example and see them detail.

Now I write an application based on dragonboat, and I want to apply production environment.

Please take a look my codes and i have some questions. 

If you can, we can communicate in Chinese, my English is poor, leads to unclear statements.

we communicated on zhihu.com private letter a few months ago.

**Comment by lni** [comment]
@xkeyideal 

Sorry but I won't review your application.

**Comment by xkeyideal** [comment]
I means the application maybe enrich the example.

So,  can you answer the above two questions

**Comment by lni** [comment]
I've just email you, please have a look. for your questions - 

1. the state machine instance is created by a user supplied factory function, users can choose whatever methods to configure their own state machine, it has really nothing to do with the raft library. 

2. Sync() is similar to Linux's fsync() API - it synchronizes the in-core state with storage device. fsync() synchronizes the state of the specified file, while dragonboat's Sync() method requires to have the state machine state synchronized.

**Comment by xkeyideal** [comment]
thx, i replied to your email, please have a look
