### ISSUE TITLE
Use Raft Log as state machine

### ISSUE THREAD

**Issue by lni** [lni/dragonboat#101]
A potential user mentioned in his email that he wants to use Raft Log as the state machine. In such setup, committed entries won't be pasted to any user state machine as the Raft Log is the state machine. User applications can query the Raft Log to get what they want.

**Comment by Fullstop000** [comment]
What's the progress of this?

**Comment by lni** [comment]
@Fullstop000 please feel free to take the ownership of this one if you like. 

Note that the issues section records all potential enhancements, when an enhancement issue is added it doesn't mean there is any concrete plan to implement it until someone pick it up.

**Comment by lni** [comment]
Infrastructures required for doing this have been added to dragonboat in the last few days. Basically - 

* there is no out of box support for using Raft Log as state machine, as you still need to define your own state machine (which should be light and straight forward). Note that such state machine should be separated from your main application logic - consider it as a metadata keeper helping your application to treat the Raft Log as a state machine.  

* Raft Logs are now exposed to users via NodeHost APIs. You can query any selected range of Raft Logs, you can request which part of the Log to be compacted, etc. 

* It would be user application's responsibility to decide how to consume Raft Log entries and maintain various indexes.
