### ISSUE TITLE
有一点忌惮对cgo的依赖.

### ISSUE THREAD

**Issue by xianglinghui** [lni/dragonboat#11]
您好，dragonboat是个挺棒的multiraft库，挺感谢开源的.

在使用介绍里，它需要依赖rocksdb、cgo，我有点忌惮对cgo的依赖(主要是对cgo了解的不深入，网上有了解到它的一些问题)，我们在基于badger(https://github.com/dgraph-io/badger，纯go的kv存储)实现一些存储，dragonboat是否可以不用依赖rocksdb、cgo?

**Comment by lni** [comment]
please use the existing issue #4 for discussing the cgo dependency. if possible, please post in english so everyone can read/help. Thanks.

**Comment by lni** [comment]
dup #4
