### ISSUE TITLE
Why not choosing a naive WAL implementation for LogDB?

### ISSUE THREAD

**Issue by yingfeng** [lni/dragonboat#115]
From the past issues I notice that RocksDB is selected as the raft log store, and others are temporarily not used due to the durability issues. 
However, as a multi-raft library, why not choose the naive log implementation instead of a KV engine? The  innegligible overhead of transaction mechanism, as well as merge operations within RocksDB which often trigger writing stalls,  could be avoided when using a naive WAL implementation. 
Most existing multi-raft database solutions also use RocksDB as the log store except for YugabyteDB, which claims the overwhelming performance compared to other competitive solutions——although it could not be conclude that it is the difference of log store that lead to the performance gap.

**Comment by lni** [comment]
Because the requirement is not that "naive".

Any plan to write (solid reliable) one for a real open source system? Will be delighted to follow that project and contribute.

**Comment by yingfeng** [comment]
Perhaps [this one](https://github.com/eBay/Jungle) could be a possible candidate.

**Comment by lni** [comment]
@yingfeng Thanks for the info. Jungle looks interesting, will definiately read its paper when I have time.  

That being said, jungle features a combation of LSM and B+-tree. With essential features like multithreaded write, truncation and crash consistency in mind, I doubt anything practical in such a production system can be regarded as "naive". ;)

**Comment by yingfeng** [comment]
Actually, [this](https://github.com/chubaodb/chubaodb/tree/e215c4f36ede33422f16676718a3d49d2f3963d6/dataserver/src/raft/src/impl/storage)  solution is what I mentioned previously, it's a real "naive" solution.

**Comment by lni** [comment]
@yingfeng I had a quick look at that Jungle paper, but I am not convinced that it is a sound solution. Please check its cost analysis results (table 1) for more details - note that there is no point/range query during dragonboat's normal operations and space amplication is not a high priority. 

ChubaoDB's log store is similar to the one used by etcd - it is a raft log store designed for single node environment.

**Comment by yingfeng** [comment]
Although the point/range query performance is not that important for raft log,  the write amplification is indeed smaller than general LSM store, so I think it might perform better than RocksDB especially when integrating Dragonboat with other persistent engines . The weakness of Jungle is it is not dedicated to log store although it claims to be because it has considered a lot on lookup performance. 
Regarding to ChubaoDB's log store, ChubaoDB itself is a multi-raft no-sql solution, so I think there exists higher abstraction for multi-raft over such that log store of single raft group.

**Comment by lni** [comment]
As mentioned by that Jungle paper itself in its table 1, its write amplification is pretty close to LSM with tiering. RocksDB support a certain type of such tiering. Known as the universal compaction, it specifically targets the high write amplification issue. Now it all comes to a simple question - why Jungle's author didn't include Jungle vs RocksDB results in terms of write amplification? See the first paragraph of page 5 for the answer. 

ChubaoDB's log store puts log entries from each raft instance to its own log file, I'd willing to bet that the fsync/fdatasync penalities on regular SSD is going to kill all performance, what happens say 2048 active raft groups all want to write the log at the same time? fsync() on 2048 files?

**Comment by yingfeng** [comment]
Yes, the "native" solution of log store, will cause serious performance issue due to concurrent fsync() from lots of WAL log files. It could be resolved through a centralized IO scheduler which calls the real fsync() while eash WAL file itself will not call fsync() directly. This is similar with many database engines, such as the [lock free WAL of MySQL 8.0](https://mysqlserverteam.com/mysql-8-0-new-lock-free-scalable-wal-design/). I have not read the sources of ChubaoDB carefully, so I'm not sure whether it has such design. Another example is YugabyteDB, there also seems to have a[ "native" log store ](https://github.com/yugabyte/yugabyte-db/tree/master/src/yb/consensus)instead of RocksDB based WAL, perhaps similar design as MySQL 8.0 exist.

Regarding to your notes for Jungle paper, I'm convinced of your conclusion :smiley:

**Comment by lni** [comment]
@yingfeng The new MySQL WAL is not that "naive". That being said, if anyone is interested and has a concrete prototype ready for integration & dicussion, I'd be more than happy to assist.

**Comment by lni** [comment]
I tried the Universal Compaction in RocksDB and it does reduce the write amplification in typical multi-raft workload. Will add that as an option so interested users can enable it if they want.

**Comment by lni** [comment]
Universal style compaction has been added, it is experimental, more testing is required before using it in production. It should be able to help reducing write amplification.
