### ISSUE TITLE
where is drummer?

### ISSUE THREAD

**Issue by huanyang712** [lni/dragonboat#120]
RT.

**Comment by lni** [comment]
Drummer is no longer provided as an open source component.

**Comment by winwisely99** [comment]
What was drummer ?

**Comment by lni** [comment]
Drummer is a program used for monkey testing dragonboat.

**Comment by prettykernel** [comment]
建议把 代码/注释/文档 中 Drummer 相关的部分也一起移除：
https://github.com/search?q=user%3Alni+drummer&type=code
