### ISSUE TITLE
Project maintenance and continuity

### ISSUE THREAD

**Issue by Iulian7** [lni/dragonboat#123]
Firstly, this is a fantastic contribution to the Go ecosystem as a whole and a much needed one at that. So really great work!

I have a couple of questions:
1. Is the library used in production anywhere?
2. This project seems to be maintained by a single person. Is it a personal project or is there a plan/roadmap to get wider adoption and support? 

Thank you,
Iulian

**Comment by lni** [comment]
This library has been used by several medium to large sized Chinese internet companies for their production systems, e.g. 58.com. There are probably many small companies using it as well. 

Contribution to the project is always welcomed.
