### ISSUE TITLE
Read Custom Index

### ISSUE THREAD

**Issue by 256dpi** [lni/dragonboat#125]
I'm currently looking into implementing linearizable sessions with dragonboat. I know that there are already API's that provide this functionality e.g. `SyncRead`, `ReadIndex`, etc. However, those guarantee linearizability over all writes and reads issued against the node.

What I'd like to do, is to get the latest index from a `Propose` result and plug that into `ReadIndex` to only wait until that specific index has been applied on the local node and then query using `StaleRead`.

Maybe this is already possible today, if not, would you be open to have it added to dragonboat. I'm happy to contribute.

**Comment by lni** [comment]
> What I'd like to do, is to get the latest index from a Propose result and plug that into ReadIndex to only wait until that specific index has been applied on the local node and then query using StaleRead.

When a proposal is completed successfully, it indicates that the proposed entry has been applied on the node where the proposal was made, you can then use StaleRead to do whatever you like.

**Comment by 256dpi** [comment]
Just to clarify: When a proposal is completed i.e. `SynPropose` returns, the entry has been committed to the local log **and applied to the state machine** even if the local node is just a follower? Up until now, I was under the impression that `SyncPropose` would return after the leader committed and applied the entry, hence the need for `SyncRead` or `ReadIndex`.

**Comment by lni** [comment]
> When a proposal is completed i.e. SynPropose returns, the entry has been committed to the local log and applied to the state machine even if the local node is just a follower?

Correct.

Note that the above described approach assumes that there is no node restart between the completion of the mentioned proposal and your stale read.
