### ISSUE TITLE
Recyclable Entry Result Data

### ISSUE THREAD

**Issue by 256dpi** [lni/dragonboat#126]
In my project I make heavy use of the possibility to attach a result to the processed state machine entry. I'm already using a buffer pool for all transformations within the update, but it seems that there is currently no way to recycle the entry result data slice.

My proposal would be to add the possibility to register some sort of callback on the result that is called once the data slice is not used anymore:

```go
type Result struct {
	Value uint64
	Data []byte

	// Releaser, if present, is called once the attached data slice is not used anymore.
	Releaser func()

	// Recycle, if present, is used to send the data slice for recycling once it is not used anymore.
	Recycle chan []byte
}
```

This not that pretty yet... I'll keep thinking.

Are you generally open to adding something like this?

**Comment by lni** [comment]
I think it is better to give users full control of what they want to return as a part of the Result struct. An interface{} is probably better here. If that gets added, the next question is whether Data []byte should be depreciated.

**Comment by 256dpi** [comment]
Based on what we discussed in #125 I assume that the result is actually set by the local node processing the state machine update? If yes, it would be amazing if there is the possibility to also attach an object to the proposal to prevent another decoding step when performing the update. The same object could the be used in return to attach a result from the update method (assuming it points to some sort of container). With that the ownership of the value is clear and no callback functionality is required.

I could imagine the following API (with backwards compatibility in mind):

```go
func (nh *NodeHost) Propose(session *client.Session, cmd []byte,
	timeout time.Duration, object ...interface{}) {}

type Entry struct {
	Index uint64
	Cmd []byte

	// Object is set to the value supplied when making the proposal if the
	//  entry is processed by the local state machine of the proposer.
	Object interface{}

	// Result is deprecated in favor of Object.
	Result Result
}
```

**Comment by lni** [comment]
> Based on what we discussed in #125 I assume that the result is actually set by the local node processing the state machine update?

Yes.

> it would be amazing if there is the possibility to also attach an object to the proposal to prevent another decoding step when performing the update. The same object could the be used in return to attach a result from the update method

It is not that straight forward. 

Consider there are three nodes in a cluster, let's call them A, B and C, assuming A is the leader. When user starts a proposal on node B, which is a follower, the proposal will have to be passed to node A first and eventually gets replicated back to B as a part of the entry replication procedure. Such attached object makes the process more complicated - shall we send it to A? we have to in the current implementation, then how to serialize/deserialize it? now A has the attached object, should A return it as well?

The biggest concern is the fact that once such attached object is allowed, different nodes will see different input Entry (two with Object set to nil, one with a concrete Object instance), this can be error prone for user's Update method - the replicated state machine model requires all raft nodes to get the exact same input Entry and return the exact same Result. 

~~To implement what you described above using the current version of dragonboat, you can generate an unique index for each proposal that requires such attached Object, somehow store the pair <index, Object> on your application side,  append the index value at the end of your proposal cmd, then you can return it as a part of your Result. On receiving such index value, your application can query and return its associated Object managed on your application side.~~

**Comment by lni** [comment]
To implement what you described above using the current version of dragonboat, you can just associate your Object with the RequestState instance returned by the Propose method and invoke the attached Object when your proposal is successfully completed. 

```
type MyRequestState struct {
  rs *dragonboat.RequestStste
  object interface{}
}
rs, err := nh.Propose(...)
if err == nil {
     ...
}
mrs := MyRequestState {
 rs: rs,
 object: yourObject,
}

// use your object when your proposal is successfully completed
```

**Comment by lni** [comment]
I was about to implement the above proposed change this afternoon, when I realized that this wasn't done in the current version for a reason - results returned by the Update method need to be associated with proposal sessions and they are marshaled and stored as a part of the snapshot util clients explicitly notify the system that they have received those results. 

When returning an interface{}, there is no way it can be marshaled/unmarshaled without letting users to implement some kind of custom marshaler/unmarshaler interface, doing that is going to make the API more complicated.

**Comment by 256dpi** [comment]
Thanks for looking in to this! Makes sense to keep an encoded version of the Update result around for the session feature.

As you pointed out, the application may store decoded versions of the command and update to prevent unneeded decoding when the request is local. In that regard, adding `Object interface{}` would just be an optimization to get rid of the global lookup map. Would be nice if it gets added, but not a big deal if not.

However, I think the initially proposed `Releaser func()` or a similar mechanism would still be ideal to release buffers back to the shared buffer pool when not used anymore. There is now way to get around this, thus it would be nice if this gets added.

What do you think?

**Comment by lni** [comment]
My concern is that this is going to make the interface slightly more complicated while the added feature is only used by very limited number of users.
