### ISSUE TITLE
Whats the best way to remove a node after it's been failing

### ISSUE THREAD

**Issue by dioptre** [lni/dragonboat#127]
If I get a lot of these errors I'd like to remove the nodehost:
```roo_roo.0.iyk7jxr4gdmt@docker2-prod    | 2020-04-14 20:14:32.809352 W | transport: breaker 192.168.9.92:6300 to 192.168.9.97:6300 failed, connect and process failed: dial tcp 192.168.9.97:6300: connect: no route to host```

What's the best approach to detect these and deal with them?

Thanks
Andrew

**Comment by lni** [comment]
It basic says the nodehost identified as 192.168.9.97:6300 is not reachable. It is up to your application to determine whether that machine actually failed or it is just connectivity issue. 

In my systems, I have separate servers to monitor all my nodehost instances, each nodehost periodically ping those servers to report it availability. A nodehost is considered as dead once it fails to send say 5 such pings in a row.

**Comment by dioptre** [comment]
Ok thanks!

**Comment by dioptre** [comment]
I implemented it this way, look ok? 
https://github.com/sfproductlabs/roo/blob/master/roo/kvwatcher.go
Had a second question too, is there a way to listen to an event for the peer that gets kicked so they can rejoin? Or do you bother?

**Comment by lni** [comment]
@dioptre 

There is a ConnectionFailed event you can subscribe to - 
https://github.com/lni/dragonboat/blob/master/raftio/listener.go#L65

To subscribe to the event, you need to implement the raftio.ISystemEventListener interface and set it here - 
https://github.com/lni/dragonboat/blob/master/config/config.go#L329

I don't use it in my system, that event listener is added to help some tests.

**Comment by dioptre** [comment]
That's great thanks mate
