### ISSUE TITLE
Add control flow for membership change

### ISSUE THREAD

**Issue by abbccdda** [lni/dragonboat#130]
The current Dragonboat membership change is limited to one node change at a time. If we are going to do a complete move of the Raft group, such as from node 1,2,3 to 4,5,6, we need six commands to make it happen. If the whole process could be automated, that would be a great efficiency saving.

In the Raft paper, there was a suggested path for maintaining two quorums during the membership change which seems to be doable, but the cost was a complexity bump for the production logic, totally not worth it just for the sake of doing flexible membership changes.

Thus we could propose a trade-off solution here, which is the `control flow` approach. Consider an example which summarizes the basic mechanics. 

Suppose that we start with a quorum consisting of the replicas (1, 2, 3) and we want to change the quorum to (4, 5, 6). When the leader receives the request to alter the quorum, it will write a message to the current quorum indicating the desired change:
```
currentVoters: [1, 2, 3]
targetVoters: [4, 5, 6]
```
Once this message has been committed to the quorum, the leader will add 4 to the current quorum by writing a new log entry:

```
currentVoters: [1, 2, 3, 4]
targetVoters: [4, 5, 6]
```

A common optimization for this step is to wait until 4 has caught up near the end of the log before adding it. Similarly, we may choose to add another replica first if it has already caught up. Once the check passes, the leader will finally send out the control record to modify the existing voter list. Once that entry has been committed to the log, the new membership takes effect. Then we could remove one of the existing replicas (say 3) by writing a new message:

```
currentVoters: [1, 2, 4]
targetVoters: [4, 5, 6]
```
Continuing in this way, eventually arrive at the following state:

```
currentVoters: [1, 4, 5, 6]
targetVoters: [4, 5, 6]
```
Suppose that replica 1 is the current leader. Before finalizing the reassignment, it will resign its leadership by sending TimeOut to other voters. Once the new leader takes over, it will complete the reassignment by removing replica 1 from the current voters. At this point, the quorum change has completed and we can clear the targetVoters field:

```
currentVoters: [4, 5, 6]
targetVoters: null
```
The previous leader will resume as a voter until it knows that it is no longer one of them. The leader will always choose to remove itself last as long as progress can still be made.

This idea was originated from another [proposal](https://cwiki.apache.org/confluence/display/KAFKA/KIP-595%3A+A+Raft+Protocol+for+the+Metadata+Quorum) I have been working on in a separate community for making membership reassignment easier.

**Comment by lni** [comment]
Thanks for sharing the idea! 

If arbitrary configuration changes is to be supported in a future release, the protocol described in the section 4.3 of the Raft thesis will be the one to be implemented. There is no excessive complexity here - just need to implement & test that well documented simple protocol plus some labor work to update all related test cases.

**Comment by abbccdda** [comment]
Ok, sounds good to me :)
