### ISSUE TITLE
How can get the count of log entries?

### ISSUE THREAD

**Issue by sosnovski** [lni/dragonboat#132]
Hi,

I would like to say thank you for the huge contribution to open source.

I had a need to track the process of applying all the log entries after the start of the node.
Tell me, is there a way to get the count of log entries at the time the node starts?

I apologize for my bad English

**Comment by lni** [comment]
when using IConcurrentStateMachine or IOnDiskStateMachine, committed proposals are provided to your Update method as Entry instances, the Index field of each Entry is the index of the committed proposal. You can use that to keep track of the progress. 

unfortunately that is not available when using IStateMachine.

**Comment by sosnovski** [comment]
I have an idea how to count the applied logs myself using the usual increment in the update method. However, the main problem is how to determine the total number of logs recorded before starting the cluster

**Comment by lni** [comment]
In raft, entry indexes are always continuous, e.g. when you have an entry with index 5 ready to be applied into the state machine, it means there must be entries with index 1,2,3,4 already committed and applied in the raft cluster. 

You might be able to figure out the total number of entries based on that.

**Comment by sosnovski** [comment]
I understood your idea, but the problem is not how to count the number of logs at the time the update method was called, but how to get their total number before starting the update method calls.

For example - in the raft library from hashicorp there is a LastIndex method
which returns the number of the last index after creating the raft instance, but before starting it.

I have a suggestion to add the ClusterReady method to ISystemEventListener. What do you think about that?

**Comment by lni** [comment]
my guess is that you want the max index of committed entries available on the local node, e.g., when there are 3 nodes in a cluster, say nodes A, B and C, when the committed index for the cluster is 100 and node C has a snapshot at index 90 plus entries between index [91, 95], you want a mechanism to somehow get this 95 value when starting C? 

for a 3 nodes cluster, when the committed index for the cluster is 100 and node C has entries [1, 101] with entry at index 101 being not committed, what value you expect to get? 

Can you also explain how such count/max index is useful to an application? Thanks.

**Comment by lni** [comment]
Closed as required information is not available.
