### ISSUE TITLE
asking for bench tools

### ISSUE THREAD

**Issue by chensheng0** [lni/dragonboat#141]
hi:

Thanks for your great work focusing on raft and distributed system.

I am new to raft and distributed consistency. And I found dragonboat, it is a amazing work as I see. So I want to learn source codes. 

Is there some bench tools? So I can do some little bench tests to see some things out, just like nats did: https://docs.nats.io/nats-tools/natsbench#start-the-nats-server-with-monitoring-enabled. Or some advice I can get some results out to help newers to learn.

Maybe it's a simple and some foolish idea, but it may do some help. Happy to see the day when I figured out some things from dragonboat.

Thanks ^_^.

**Comment by lni** [comment]
There is no plan to provide any benchmarking tool.
