### ISSUE TITLE
How does dragonboat manage clock drift (or skew)?

### ISSUE THREAD

**Issue by Ichliebedich0505** [lni/dragonboat#142]
In the section 8 of raft thesis, the authors assume that the clock skew is bounded so that the leader lease can be employed to ensure the leader won't step down for some time to come. But the clocks in servers must be different to some extent. Here I wonder how does dragonboat manage clock drift (or skew)?

**Comment by lni** [comment]
Please follow the instructions in issue_template.md when raising issues. 

If you are interested in certain part of Dragonboat's design/implementation, please read the source code, the answer is there. When you believe something is broken/missing, please be more specific on what you saw/experienced. Thanks.
