### ISSUE TITLE
PebbleDB Memory Settings

### ISSUE THREAD

**Issue by jkassis** [lni/dragonboat#145]
Is there a way to control memory usage of pebble through dragonboat?

eg badger gives some control over memory mapping for LSM tables and allows the user to specify maximum ram size for cache.

not seeing these options in the pebble codebase, so i'm guessing no, but raising it here in case i missed something.

**Comment by lni** [comment]
Please have a look at the LogDB field in config.NodeHostConfig, it is defined in config/config.go
