### ISSUE TITLE
RTTMillisecond Tuning

### ISSUE THREAD

**Issue by jkassis** [lni/dragonboat#147]
What's the best way to measure RTTMillisecond? And... does RTTMillisecond affect the overall bandwidth of the system?

After resolving `https://github.com/lni/dragonboat/issues/146` by switching to rocks... I'm trying to get the overall bandwidth of my system up.

The documentation for RTTMillisecond suggests that it could be as low as 1ms, but some of the other docs suggest values of 100.

**Comment by jkassis** [comment]
Also. What's a good rule of thumb for log compaction. How many raft proposals. More proposals == more compaction == less time for proposals.

**Comment by lni** [comment]
Please see the godoc of NodeHostConfig.RTTMillisecond on its definition, it has been clearly defined there. Note that there is no suggested RTTMillisecond, it should be set to reflect the working environment of your system. 

Closing this one as from my point of view the RTTMillisecond field is well defined/explained in godoc, in case you find the godoc to be hard to understand, please feel free to reopen and be more specific on what makes you find it is hard to to understand so we can have a look and improve from there. 

Please open a new issue for log compaction, as explained before, I'd like to make the issue section easy for all users to search & read by limiting the scope of each issue to the one described by its title.

**Comment by jkassis** [comment]
the docs are good WRT the definition of RTTMillisecond: `// Note that RTTMillisecond is the combined delays between two NodeHost including all delays caused by network transmission, delays caused by NodeHost queuing and processing`.

The question is more about the best way to measure it. Does Dragonboat expose an internal prometheus metric for this?

if i were to measure it myself, i would probably expose total time for write proposals and subtract total time inside my rafted service.

does that seem like a reasonable approach?

**Comment by jkassis** [comment]
Also, the other part of the question is what impact does RTTMillisecond have on performance? 

What is the impact of it being set to a value less than the actual RTT?

And what about being set to a value much greater than the actual RTT?

It seems clear that this parameter would affect average latency. But what about bandwidth? I would guess that a large RTT forces more proposals into large batches.

If it is measurable internally, would you consider a feature request for the system to automatically tune / retune itself using a fast moving average to get optimal results?

**Comment by lni** [comment]
Unless you have very large number of Raft clusters, RTTMillisecond is expected to have small impact on proposal throughputs.
