### ISSUE TITLE
SnapshotEntries Tuning

### ISSUE THREAD

**Issue by jkassis** [lni/dragonboat#149]
What's a good rule of thumb for SnapshotEntries / log compaction?

I do understand that this is application specific, but perhaps some extra general guidance related to this value? Something like an equation perhaps?

I have noticed that <SnapshotEntries == more compaction == less time for proposals == smaller WAL size == faster node synchronization when sizeof(Entry) / sizeof(Snapshot) is large.

I had snapshot entries set to 2048 and snapshotting was blocking the raft at high TPM for my RSM implementation. Disk-Backed statemachine is better.

**Comment by lni** [comment]
Users have full control on when they want to have a snapshot generated. You don't have to use Config.SnapshotEntries to make a snapshot for every N proposals. RequestSnapshot and SyncRequestSnapshot can be called at any time to generate a snapshot. It is up to the user to decide when it is appropriate to generate a snapshot as there are many factors involved. 

Also note that LogDB compaction is not compulsory - you can disable the auto compaction and request compaction whenever you think necessary.  

OnDisk state machine has all states stored on disk already, so it only saves the tiny metadata of the state machine when generating a snapshot. In memory state machines on the other hand have to store the whole in memory RSM state to disks.

I think the rule of thumb here is to know your hardware/software and take snapshots/compactions when necessary.
