### ISSUE TITLE
Restore cluster after nodes crash and lost quorum 

### ISSUE THREAD

**Issue by ikgo** [lni/dragonboat#150]
### Dragonboat version
v3.0.0 master branch

How restore cluster after crash of nodes and cluster lost quorum and failed nodes can't be started with same IP?
NodeHost.RequestDeleteNode and RequestAddNode returns error in case cluster in not operational mode.

### Steps to reproduce the behavior
- 3 nodes cluster up and running.
- two nodes crushed
- two new nodes started but with new IP's

**Comment by jkassis** [comment]
@ikgo sounds like you might want to read `https://github.com/lni/dragonboat/issues/140`

**Comment by lni** [comment]
@ikgo 

When 2 nodes out of your 3 nodes cluster are unavailable, the state of your Raft cluster becomes unavailable. You will not be able to use any membership change request (such as NodeHost.RequestDeleteNode and RequestAddNode) to remove or replace the crashed nodes as the cluster no longer has quorum to complete those operations. 

When those 2 nodes are permanently gone, your only option is to use two new nodes and call tools/ImportSnapshot to fix your Raft cluster. Some of committed proposals made by the cluster will be lost, as Raft require the quorum of the cluster to be available to ensure no committed proposals will ever be lost, but it can restore the cluster to an available state. Please read the doc in tools/import.go for details. 

Note that if any one of those two nodes can be restarted with the same IP or DNS name, as 2 out of the 3 nodes will become available, you will then be able to use those membership change methods to replace the 3rd unavailable node with a new one. 

If all your nodes have dynamic IP addresses assigned to them on rebooting, then you can consider the DNS name approach mentioned in #140. The coming v3.3 release will also allow users to address their NodeHost instances using their UUID values by using a custom build transport layer. The custom transport layer has the responsibility to discover and map UUID to reachable NodeHost addresses. nodehost_test.go has a test named TestTransportModuleCanUseUUID which basically demonstrates such use case.

**Comment by ikgo** [comment]
@lni thanks
