### ISSUE TITLE
Is this project dead?

### ISSUE THREAD

**Issue by sethyates** [lni/dragonboat#152]
This looked very promising in my initial tests, but I'm finding a few issues and there seems to have been very low activity this year. Is this project is dead?

**Comment by lni** [comment]
there were almost 1,000 commits to dragonboat and its related examples/tools in the last 12 months. what is your definition of low activity? 

please stop spreading such nonsense that can have negative impact on open source projects. 

I will delete this issue from the issues section in 24 hours.
