### ISSUE TITLE
RocksDB Compatibility Verification

### ISSUE THREAD

**Issue by jkassis** [lni/dragonboat#157]
I'm currently running Rocks 6.14 in production. What's the best way to test for complete compatibility with Pebble during migration to v3.3?

### Dragonboat version
v3.3

**Comment by lni** [comment]
Pebble claims to be compatible with RocksDB v6.2.1. 

In my own tests, I have a test Raft based program that keeps switching between RocksDB v5.18.x and Pebble during restarts. The test program checks whether everything work as expected and whether all Raft replicas end up having the same Raft Logs. A recently added LogDB plugin called Tee uses both RocksDB and pebble side by side so each read can be verified to see whether results are identical between those two KV stores. v3.3 and its default pebble version is known to pass both of these tests. 

During your migration, if you believe it is important to further run some verifications yourself, you may want to use some of the above described approaches. 

Note that Dragonboat only uses a small subset of features in RocksDB/pebble (batch write, iterator, get and manual compaction). If you use Pebble in your own application (e.g. in the state machine), then it is up to you to further verify your needs.

**Comment by jkassis** [comment]
Excellent answer. Thank you @lni
