### ISSUE TITLE
Gossip: 3 node cluster with one node down => quorum will be lost

### ISSUE THREAD

**Issue by stffabi** [lni/dragonboat#159]
If gossip is used with a 3 node cluster and one node is down, the gossip `NodeHostIDRegistry` can't resolve the node anymore from the NodeHostID to the RaftAddress, returning an error to the transporter. The transporter uses in its `send` method one common CircuitBreaker for all `IResolver.Resolve` calls.

https://github.com/lni/dragonboat/blob/ca6b5cabf3afd2da1083892f9cf04ffd3bcde623/internal/transport/transport.go#L363-L373

Due to the common CircuitBreaker not only sends to the node which is down will fail, but also sends to the 2 other available nodes will fail, because the CircuitBreaker might not be ready (triggered by the failing node). As a result the cluster will become unstable changing switching between Ready and NotReady depending on the CircuitBreaker introduced fails to the other 2 nodes.

### Dragonboat version

v3.3.0

### Expected behavior

Gossip based 3 node cluster is stable and usable even if one node is down.

### Actual behavior

Cluster becomes unstable => changing between Ready and NotReady

### Steps to reproduce the behavior

Create 3 node gossip based cluster and take one node down.

**Comment by stffabi** [comment]
I've tried to create a PR with a fix and pushed it as a Draft PR for discussion.

**Comment by lni** [comment]
Thanks for reporting! I think that circuit breaker was there by mistake - the gossip based address resolver queries its in memory member list to get the address, having a circuit breaker there isn't saving any resources, it is actually causing each sent message to have to get and update that circuit breaker. From memory, I added that when I saw excessive logging messages in tests, it was probably added to temporarily suppress them but I forgot to get it removed. 

I'd recommend to have that circuit breaker removed. What do you think? 

A related issue here is that the current implementation queries the node list returned by the memberlist library, it is not scalable when there are say thousands of NodeHost instances, as each sent message must iterate through thousands of memberlist node instances to get the address. I will address this one.

**Comment by lni** [comment]
the above mentioned related issue has been fixed. That redundant circuit breaker is still there, you may want to remove it in your PR or I can just delete it. Thanks for reporting the issue.

**Comment by stffabi** [comment]
@lni I'm fine with removing the circuit breaker. I've just updated the PR. Thanks for fixing/optimizing the the memberlist iteration.
