### ISSUE TITLE
OnDiskSM: PrepareSnapshot is called for dummy snapshot, how to release resources

### ISSUE THREAD

**Issue by stffabi** [lni/dragonboat#162]
In the current implementation `PrepareSnapshot` is called when a dummy snapshot gets created for an OnDiskSM. Most often an OnDiskSM needs to open some resources in the `PrepareSnapshot` method, e.g. a Pebble Snapshot, which needs to be closed after it is not used anymore. A close of the Pebble Snapshot e.g. is needed in order to allow Pebble to delete entries that are prevented from the snapshot to be deleted from the disk.
Currently there's no reliable way to close the Snapshot, for a normal Snapshot the close can be done in the `SaveSnapshot` method. But for a dummy snapshot obviously `SaveSnapshot` is not called because it is dummy and contains only metadata.

### Dragonboat version
v3.3.0

### Expected behavior
The `PrepareSnapshot` should not be called for a dummy snapshot.

### Actual behavior
The `PrepareSnapshot` is called for a dummy snapshot and there's no way for the OnDiskSM to close the snapshot to free resources.

**Comment by lni** [comment]
Thanks for reporting this issue. I am going to fix it today and make it into v3.3.1.

**Comment by stffabi** [comment]
@lni Thanks for fixing the issue and creating a new release.
