### ISSUE TITLE
Client SyncPropose outcome based on the IStateMachine update Callback Status

### ISSUE THREAD

**Issue by rajeshkgit** [lni/dragonboat#164]
I am trying to explore the multiraft for Application State replication( Application state is persisted to a persistent backend such as PostgreSQL or other databases). I have modified the HelloWorld IStateMachine to update the database as part of the Update() invocation, however, I am not able to fail the client SyncPropose based on the DB Update status (any error in updating the database should fail the entire client operation). Returning Sm.result with Value zero does not seem to have any effect and a non-nil error is crashing the client. How should I achieve the Client Proposal that also depends on the failure/success of the application state update?

**Comment by lni** [comment]
As documented in statemachine/rsm.go, any non-nil error returned by the Update() method is considered as "unrecoverable", it will cause dragonboat to panic as there is no other sensible action it can take. For example, the disk or memory is full when you want to write something to it. So only return a non-nil error when you believe such error requires the whole program to be terminated so you can resolve the issue and restart/retry later. 

In your own application, there might be some application logics that can return "errors", e.g. primary key conflict when inserting a new record. When your application can handle them, they are not really errors from Replicated State Machine's point of view, they are just part of the features. For those kinds of "errors", you should encode them into sm.Result so your client can receive and handle them accordingly. 

btw, when your RSM state is persisted, you should use the IOnDiskStateMachine.

**Comment by lni** [comment]
#166 contains some detailed explanation as well
