### ISSUE TITLE
A quick question: Were benchmarks data based on default tcp transport?

### ISSUE THREAD

**Issue by chensheng0** [lni/dragonboat#168]
I am reading the source code, and saw dragonboat has an excellent performance which according to benchmarks data. Is these data were test base on  default tcp transport or other customed rpc transport.

Thanks a lot.

**Comment by lni** [comment]
Default TCP transport on 40Gbps dual ports ethernet cards. 

Note that the benchmark results were observed on 2 years old open source version. Most recent internal version is about 50% better in terms of throughput, latency is also significantly reduced.

**Comment by chensheng0** [comment]
Thanks a lot.
