### ISSUE TITLE
请问 startCluster 的时候 join 是如何使用的？

### ISSUE THREAD

**Issue by huanyang712** [lni/dragonboat#169]
请问 startCluster 的时候 join 是如何使用的？
有没有相当文档？

···
if join && len(initialMembers) > 0 {
		return ErrInvalidClusterSettings
	}
···

我看到了这段代码，如果join=true的时候，却不能设置initialMembers，
那么，请问当前启动的node，要  join 到哪里去呢？

**Comment by lni** [comment]
Please see the godoc of the StartCluster method.
