### ISSUE TITLE
A quick question: when will follower response leader replicate RPC request?

### ISSUE THREAD

**Issue by Petelin** [lni/dragonboat#17]
i am reading the source code, and found the follower simple accept log from leader and append to slice(not to DB or say Persistence). that's not what RAFT protocol said.
am i read code wrong or something else? thanks for you time.

**Comment by lni** [comment]
@Petelin, You are probably reading the code in internal/raft. 

Log entries are persisted to disk under the coordination of the Execution Engine implemented in execengine.go. The actual DB used for storing such entries is called LogDB and its default implementation is in internal/logdb.
