### ISSUE TITLE
Corruption: While creating a new Db, wal_dir contains existing log file

### ISSUE THREAD

**Issue by xkeyideal** [lni/dragonboat#170]
Dragonboat version: v3.2.8
rocksdb version: 6.14.6

restart cluster:

![image](https://user-images.githubusercontent.com/6369390/112956775-619edd80-9173-11eb-870e-abab83ca8432.png)

restart cluster repeatedly:

![image](https://user-images.githubusercontent.com/6369390/112956925-885d1400-9173-11eb-8d80-2334f3c86554.png)

**Comment by lni** [comment]
The RocksDB instance used for storing Raft logs and metadata is corrupted. 

When trying to restart your instance, RocksDB believed that it is a new DB (in pebble, which can be considered as a golang port of RocksDB, this means there is no CURRENT file in the db directory, not sure how RocksDB itself checks whether it is a new DB) but later found existing .log files in the folder pointed by the wal_dir. Any chance you changed your NodeHostDir and WALDir settings in your NodeHostConfig between restarts? 

I'd recommend to get this instance permanently removed to avoid affecting other nodes. There are at least two replica nodes with the same data.

**Comment by xkeyideal** [comment]
The program didn't modify NodeHostDir and WALDir settings, I found the CURRENT file in the db directory DATADir lost any data and WALDir log exist. 
So RocksDB believed that it is a new DB,  but WALDir contains existing log file.

I don't know why this happens, now I deploy the program to linux test environment and observe for a few days.

**Comment by xkeyideal** [comment]
The program didn't modify NodeHostDir and WALDir settings, I found the CURRENT file in the db directory DATADir lost any data and WALDir log exist. 
So RocksDB believed that it is a new DB,  but WALDir contains existing log file.

I don't know why this happens, now I deploy the program to linux test environment and observe for a few days.

**Comment by lni** [comment]
you may want to upgrade to latest version v3.3.1, v3.2.x is no longer maintained.

**Comment by xkeyideal** [comment]
> you may want to upgrade to latest version v3.3.1, v3.2.x is no longer maintained.

Thanks
