### ISSUE TITLE
Feature request: API access to LogDB

### ISSUE THREAD

**Issue by coufalja** [lni/dragonboat#175]
Hello, we run multiple multi-group dragonboat clusters which currently synchronise their state using Kafka. We would like to implement an asynchronous replication in a hub-and-spoke manner in between the clusters.  For that purpose, we either implement binlog as a state machine or given the date are already stored in the log in LogDB already access it there. 
* Is there a reason why not to allow access to LogDB via NodeHost instance?
* I can capture the LogDB via LogDBFactory wrapper but that feels ugly and wrong :)
* What would @lni say for having Readonly access to LogDB (via some Readonly LogDBWrapper)? - I can prepare a PR
* Did I miss some obvious way how to achieve the result with the current APIs? (e.g. watcher or Raft, in general, is not suitable because of its synchronous nature)

**Comment by lni** [comment]
> Is there a reason why not to allow access to LogDB via NodeHost instance?

The biggest reason is that the vast majority of users don't care the Raft logs stored in the LogDB. Exposing the LogDB via NodeHost is going to make NodeHost more complicated. Keeping it private also allows the LogDB interface to be changed without affecting any user applications. 

I can see legitimate reasons why certain applications would require access to the LogDB, as I have an application that requires this feature as well. 

Could you please provide some more details on what you plan to add in your PR? Thanks.

**Comment by coufalja** [comment]
No specific plans yet, I was thinking about creating a new interface in `raftio` package that would define read-only methods for LogDB (effectively a subset of current `raftio.ILogDB`). And the implementation should be a wrapper struct around the actual LogDB implementing the aforementioned interface via delegation to the actual DB. Via the split, I would have got the feature I need while keeping the flexibility in the core/internal package as the `raftio.ILogDB` interface could possibly change independently of the read-only Interface.

**Comment by lni** [comment]
@coufalja 

How about we add another API to NodeHost named GetReadOnlyLogDB(), it returns a LogDB wrapper that implements the existing raftio.ILogDB interface but all write related methods will cause panic in this wrapper?
