### ISSUE TITLE
RequestAddNode   error

### ISSUE THREAD

**Issue by cnkidong** [lni/dragonboat#179]
> in muti raft group , when i call  RequestAddNode  make member change,
 the console shows **"[error] request rejected as it is out of order**"
the code below:
ctx, cancel := context.WithTimeout(context.Background(), 10*time.Second)
	defer cancel()
	memberShip, err := nodehost.SyncGetClusterMembership(ctx, uint64(intClusterID))
	if err != nil {
		log.Errorf("get membership failed, %v", err)		
		return
	}
	rs, err := nodehost.RequestAddNode(xx, xx, xx, memberShip.ConfigChangeID, 10*time.Second)
	if err != nil {
		log.Errorf("membership change failed, %v", err)
		return
	}
	s := <-rs.ResultC()
	if s.Timeout() {
		// the request failed to complete before the deadline, maybe retry the
		// request
		log.Errorf("the request failed to complete before the deadline")		
	} else if s.Completed() {
		rs.Release()		
		log.Infof("membership change completed successfully")	
	} else if s.Terminated() {
		// request terminated as the system is being shut down, time to exit
		log.Errorf("request terminated as the system is being shut down, time to exit")
	} else if s.Rejected() {
		// request rejected as it is out of order. try again with the latest order
		// id value returned by NodeHost's SyncGetClusterMembership() method.
		log.Errorf("request rejected as it is out of order")
	} else {
		log.Errorf("membership change failed")
	}
### Dragonboat version v3.3.1

**Comment by lni** [comment]
@cnkidong I guess you've figured out the problem by yourself. 

I've also added a test named TestOrderedMembershipChange in nodehost_test.go, it seems to me that the involved add node with constrained config change ID feature works as expected.
