### ISSUE TITLE
Store previous gossip configuration

### ISSUE THREAD

**Issue by lebovski** [lni/dragonboat#199]
When using a raft without gossip, I need to send the config once. For the gossip option, I should always use config. Is it possible to create a launch option that will allow configuring the gossip protocol without config.

Example.
We set the parameters of the gossip protocol through a method call, and not through a config or through a constructor, while the configuration is remembered by the cluster and can be updated in the future. On restart, if there were no changes, we do not need to pass anything to the constructor related to the gossip protocol.

Is something like this possible?

**Comment by lni** [comment]
@lebovski please note that when using dragonboat without gossip, you do need to specify configuration every time when you restart your nodes. 

I think user applications should always be explicit on what configurations they want to use and the best way to do that is to let the applications explicitly provide such configurations on each reboot.  

Is there any particular reason why you would like to change this?
