### ISSUE TITLE
Allow to set NodeHostID in config

### ISSUE THREAD

**Issue by lebovski** [lni/dragonboat#200]
It is not always possible to poll all nodes and get their nhid. Cluster configuration is simplified if I can set the identifier myself. I would like to be able to set it from the config.

Currently, the identifier can be set only by specifying the TestNodeHostID.

**Comment by lni** [comment]
You can set it via the following field. 

https://github.com/lni/dragonboat/blob/ea6f310feeb6fa61677857eb00099f5d34851987/config/config.go#L939

It is not provided as a regular configuration field as I don't want to make the configuration too complicated for regular users. Note that once you set your own NodeHostID via configuration, you will be responsible for making sure that the unique ID is always used for the same NodeHost instance, changing the NodeHostID value after reboot will bring unexpected consequences.
