### ISSUE TITLE
Promoted Observer is unable to reconnect

### ISSUE THREAD

**Issue by intrntbrn** [lni/dragonboat#204]
### Dragonboat version
3.3.4

### Expected behavior
After successfully promoting an observer, the node should be able to reconnect as non observer.

### Actual behavior
The node is unable to reconnect as non observer (panic).

### Steps to reproduce the behavior
1. A node n is added to the cluster as observer (via `nh.RequestAddObserver`)

2. n joins the cluster (via `nh.JoinOnDiskCluster` with IsObserver=true in config)

3. The leader of the cluster promotes n to a regular voting node (via `nh.RequestAddNode`).

4. The changes are reflected in the updated membership config.

5. n restarts/crashes.

6. n tries to rejoin the cluster with IsObserver=false in config. 

7. dragonboat panics: "t2 is not an observer".

8. n is able to rejoin as observer though (despite being promoted). However, according to membershipconfig there are no observers in the cluster.

**Comment by lni** [comment]
I can be wrong but from memory you should restart your node n with IsObserver = true. Its state will be set to regular voting node when the promotion config change entry is applied directly or via a snapshot. 

Could you please try this and share the outcome here? Thanks.

**Comment by intrntbrn** [comment]
This seems to be case. After rejoining with IsObserver=true and applying the entries, the node was able to become the leader of cluster after crashing the previous leader.

In my application another coordination process keeps track of all shards, the participating nodes and their roles. 
To work around this issue, the coordination process now has to keep track of the current role *AND* the initial role of a node in a cluster. This seems counterintuitive.
Any plans to fix this? Is the IsObserver flag in the config actually necessary in the first place?

**Comment by intrntbrn** [comment]
Also, is there a way to tell if an observer has received all entries (is uptodate) and therefore is safe to be promoted?

**Comment by lni** [comment]
@intrntbrn for most applications, you don't have to explicitly keep the initial role, e.g. for new nodes joining into existing raft clusters, if you always create observers first and then promote them to voting members, you can always assign fixed & known nodeID values to raft cluster's initial members but other nodeID values for such observers. By doing that, you can figure out whether a node was initially launched as an observer. 

There is currently no easy way to tell whether an observer has caught up with the leader. Any PR in this aspect will be welcomed.
