### ISSUE TITLE
the Update method

### ISSUE THREAD

**Issue by carr123** [lni/dragonboat#205]
hello, this is not a issue,  i have a  question to ask you.
i implement an OnDiskStateMachine, and set it to dragonboat system.
is it possible that the Update method in IOnDiskStateMachine are invoked by two goroutines at the same time ?
thanks.

**Comment by lni** [comment]
No, for the same node, its Update method implemented as a part of the IOnDiskStateMachine interface will never be invoked concurrently by two goroutines. The Update method will always be invoked sequentially in the same goroutine.
