### ISSUE TITLE
custom logger

### ISSUE THREAD

**Issue by carr123** [lni/dragonboat#206]
hi, i implement my own ILogger, and could you tell me how can i set it to dragonboat ?
the default logs in dragonboat are written to stderr/stdout, so i want to use my own log system.
thanks.

**Comment by lni** [comment]
Please use the factory function linked below. 

https://github.com/lni/dragonboat/blob/7db91bd26f838034603319ae0a3ea50e49cb0126/logger/logger.go#L59
