### ISSUE TITLE
how to control batchsize 

### ISSUE THREAD

**Issue by carr123** [lni/dragonboat#207]
IOnDiskStateMachine.Update(entrys []sm.Entry) ([]sm.Entry, error)

hi，is there any config that i can control the max number of entrys at a time?
i worry if there are too many entries, the underline database could fail to operate in a single batch.

thanks.

**Comment by lni** [comment]
@carr123 there is no such configuration available atm. 

you can easily control the number of entries to apply in one batch within your Update() method, e.g.

consider your Update() is called with 4 elements in its input parameter "entries []sm.Entry" when there Entry.Index is 100 to 103, you can write those 4 sm.Entry instances to the db in 2 batches, that is you can apply the first two sm.Entry instances and their highest Entry.Index = 101 atomically into the db in on batch, then apply the remaining two sm.Entry instances and their highest Entry.Index = 103 atomically into the db in the second batch.
