### ISSUE TITLE
how to find raft group nodes ?

### ISSUE THREAD

**Issue by carr123** [lni/dragonboat#208]
hi, i have 6 server nodes (n1, n2, ... n6). n1, n2, n3 are running raft group1 while n4, n5, n6 are running raft group2.
if a client request is coming on n1, it finds the data is on raft group2(data is hashed to raft group2), how can the client find where the raft group2 nodes are and route request to them ?
tnanks.

**Comment by lni** [comment]
it is completely up to your application to implement such feature. e.g. you can use gossip style service to maintain such data partition details or you can even use a centralized server to manage such info.

**Comment by carr123** [comment]
thanks very much
