### ISSUE TITLE
Can not change system hostname

### ISSUE THREAD

**Issue by lebovski** [lni/dragonboat#209]
The hostname is used to form the path and is further verified. Is there a need for this? Alternatively, you can make an option without checking hostnames.

### Dragonboat version
v3.3.4

### Expected behavior
Error, if hostname changed.

### Actual behavior
Configurable behaviour.

### Steps to reproduce the behavior
1. Run dragonboat first.
2. Stop dragonboat.
3. Change hostname.
4. Run dragonboat.

**Comment by lni** [comment]
Please consider the situation in which the SSD of a machine from a production cluster is taken offline and then installed onto a test cluster, with the same ClusterIDs and matching NodeIDs, things can become pretty funny.

Yes, I agree that an option to skip such checks can be useful. Could you please provide a PR for that? Thanks.

**Comment by lebovski** [comment]
Thx, I will try to do it.
