### ISSUE TITLE
automatic assignment of identifiers for nodes

### ISSUE THREAD

**Issue by uber42** [lni/dragonboat#211]
Now I am trying to set up automatic deployment of the cluster and I need to somehow automatically set the identifier for the nodes

So far identifiers are set when adding each node manually, but due to the fact that some node could be removed, it may turn out that the specified identifier of the node may already exist in the cluster, then to the addition will be completed with an error

There is an idea to increment the identifier at the level of the cluster logic and not set it manually, but in order for such logic to be consistent and the identifiers do not intersect, a quorum condition is necessary, which is undesirable when changing the composition of the cluster, are there any ways to achieve automatic assignment of cluster identifiers?

**Comment by lni** [comment]
You can use random 64bit integer as nodeID. As long as it is truly random (let's don't go deep on the definition here :)), it should be extremely unlikely to have any collision. 

Also note that a new node with assigned nodeID must be added to the raft group by using the membership change API first. When doing that, dragonboat has code to check whether the nodeID is valid including whether it is the same as a removed nodeID. Your membership change will be rejected if the nodeID is invalid. In short, even if you are lucky enough to have a collision of such random nodeID, you can simply just retry after being rejected by the above described membership change operation.
