### ISSUE TITLE
Make minor release.

### ISSUE THREAD

**Issue by lebovski** [lni/dragonboat#213]
Many allocations have been found with applyWorkerMain. The fix is already in master. Can a minor release be released (v3.3.5)?

**Comment by lni** [comment]
Yes, it makes sense to make a minor release. I will make it this coming weekend.

**Comment by lebovski** [comment]
thanks

**Comment by lebovski** [comment]
Hello, can we make minor release?

**Comment by lni** [comment]
@lebovski sorry for the delay, it is done now. 

please report bugs if you see any. thanks.

**Comment by lebovski** [comment]
Thanks!!!!
