### ISSUE TITLE
[Help]Listening for cluster changes

### ISSUE THREAD

**Issue by Cloud33** [lni/dragonboat#215]
Recently, I am using the `dragonboat` software package to write a distributed system, and each node of the system will complete the whole work. When a node fails, its work results will be lost, and then I need to let other nodes run their work again. However, `dragonboat` does not provide any API for adding callbacks, nor can it listen for the status of all nodes in the cluster. What should I do?

Did I miss anything?

thank you

**Comment by lni** [comment]
What you need is some node state monitoring feature, this is outside the scope of the dragonboat library. dragonboat is a consensus library, it does one thing and one thing only - consensus using the raft protocol.

**Comment by Cloud33** [comment]
Yes, thank you
