### ISSUE TITLE
Implement gRPC TransportFactory

### ISSUE THREAD

**Issue by intrntbrn** [lni/dragonboat#219]
I am trying to implement a custom `TransportFactory` using gRPC. My application already uses gRPC for internal communication and want to share the tcp port using a connection multiplexer (http(s), grpc, etc. on the same port).

I've noticed that commit https://github.com/lni/dragonboat/commit/4465a0baf1bba95e74d7e025c9f66256fc012fe4 removed `raft.proto` that i somehow need to import in order to send `pb.MessageBatch` and `pb.Chunk`. Is there a way to workaround this issue? 

Also, gRPC transport seems like a common implementation. Why does dragonboat not provide an option to use gRPC by default? Is it that much slower than the current transport implementation?

//Edit: I managed to import the proto file, but i had to modify it:

So when using a stable version (e.g. v3) i am still able to access to `raft.proto`. 
I can include the file in my own proto file by using `import  "github.com/lni/dragonboat/v3/raftpb/raft.proto";` after running `go mod vendor` and including the path in `protoc` (e.g. `protoc -I=./vendor ...`). 
However,  this results in an error: 
```
protoc-gen-go: unable to determine Go import path for "github.com/lni/dragonboat/v3/raftpb/raft.proto"

Please specify either:
        • a "go_package" option in the .proto source file, or
        • a "M" argument on the command line.

See https://developers.google.com/protocol-buffers/docs/reference/go-generated#package for more information.

--go_out: protoc-gen-go: Plugin failed with status code 1.
```

This error can be fixed by providing the required go_package in `raft.proto`: 
`option go_package = "github.com/lni/dragonboat/v3/raftpb";`

**Comment by lni** [comment]
@intrntbrn

I am not a big fan of protobuf or gogoprotobuf, that is why they've been removed. Assuming gRPC requires just a marshaler and an unmarshaler, you can probably just implement those required interfaces for the message batch type. 

Note that the marshaler/unmarshaler methods in the current code base are not generated by protobuf/gogoprotobuf. 

Please also note that there was a gRPC transport module in dragonboat, you can see it in old releases. Its support was dropped as I believe it is inefficient to use gRPC or any other RPC libraries for streaming raft replication messages.
