### ISSUE TITLE
performance tunning

### ISSUE THREAD

**Issue by hnwyllmm** [lni/dragonboat#22]
do you have performance tunning document?
or some parameters?
@lni

**Comment by lni** [comment]
Please have a look at the internal/settings package, there are some parameters you can tune. 

Note that anything in the Hard category should not be changed once your system is deployed, otherwise NewNodeHost can fail with a warning indicating such errors. You can freely change those in the Soft category. There are some descriptions on each parameter. 

Also note that being as a part of the internal/* packages means it is not considered as a part of the public API. Any parameter there can be renamed/removed/changed at any further release without any notice in advance. Please consider it as an expert option only suitable for someone quite experienced with Dragonboat's internals. 

I am going to close this one, if you have specific question on any particular parameter, please raise new issues so such questions can be easier to search/read by other users.

**Comment by lni** [comment]
btw, such tuning requires good working understanding on Dragonboat's internals, a pretty good example on what constitutes for such working understanding is that when you feel comfortable to make significant changes/bug fixes to dragonboat. 

I wouldn't recommend anyone to start doing performance tuning without such solid experience on Dragonboat - by default, it is already significantly faster than all other free & open source raft libraries

**Comment by hnwyllmm** [comment]
> btw, such tuning requires good working understanding on Dragonboat's internals, a pretty good example on what constitutes for such working understanding is that when you feel comfortable to make significant changes/bug fixes to dragonboat.
> 
> I wouldn't recommend anyone to start doing performance tuning without such solid experience on Dragonboat - by default, it is already significantly faster than all other free & open source raft libraries

I modified the example helloword for performance test. The result is very bad.
```
[wangyl11@host-10-19-18-65 helloworld]$ ./helloworld -nodeid 1 -thread_num 400
node address: localhost:63001
2019-01-23 15:37:42.294985 I | logdb: RangeDelete is disabled in ShardedRDB
duration: 10, count: 2104785, tps: 210478.500000
duration: 10, count: 37527, tps: 3752.699951
duration: 10, count: 38026, tps: 3802.600098
duration: 10, count: 25211, tps: 2521.100098
duration: 10, count: 35225, tps: 3522.500000
duration: 10, count: 39224, tps: 3922.399902
duration: 10, count: 31619, tps: 3161.899902
duration: 10, count: 23228, tps: 2322.800049
duration: 10, count: 35226, tps: 3522.600098
duration: 10, count: 34016, tps: 3401.600098
duration: 10, count: 18419, tps: 1841.900024
duration: 10, count: 31223, tps: 3122.300049
duration: 10, count: 28015, tps: 2801.500000
duration: 10, count: 25214, tps: 2521.399902
duration: 10, count: 43226, tps: 4322.600098
duration: 10, count: 21610, tps: 2161.000000
duration: 10, count: 26010, tps: 2601.000000
```
400 concurreny, about 2500TPS. It's unacceptable.
Surely, we have no device like NVME. But  the result of `braft`  is 70000 - 80000 tps at the same machine.

**Comment by lni** [comment]
Please put your modified code to a repo so it can be verified. I don't think it is appropriate to make such claims without anything to back your claim. 

Note that when using a single raft group, as reported in README.md, Dragonboat can achieve more than 1 million proposals per second.

**Comment by lni** [comment]
@hnwyllmm , back-of-the-envelope calculation shows when concurrency is 400, if the tps is 2500, that is pretty much 6.25 requests per goroutine per second, or 160ms to complete a single proposal. 10000/7200rpm HDD has a disk latency of around 2-4ms. 

It is actually pretty hard to intentionally slow down the program to that kind of performance.

**Comment by hnwyllmm** [comment]
here is diff information of https://github.com/lni/dragonboat-example:
```
diff --git a/helloworld/main.go b/helloworld/main.go
index fdcadfb..5ef403c 100644
--- a/helloworld/main.go
+++ b/helloworld/main.go
@@ -114,6 +114,7 @@ func main() {
 	nodeID := flag.Int("nodeid", 1, "NodeID to use")
 	addr := flag.String("addr", "", "Nodehost address")
 	join := flag.Bool("join", false, "Joining a new node")
+	thread_num := flag.Int("thread_num", 0, "Thread number")
 	flag.Parse()
 	if len(*addr) == 0 && *nodeID != 1 && *nodeID != 2 && *nodeID != 3 {
 		fmt.Fprintf(os.Stderr, "node id must be 1, 2 or 3 when address is not specified\n")
@@ -145,9 +146,10 @@ func main() {
 	fmt.Fprintf(os.Stdout, "node address: %s\n", nodeAddr)
 	// change the log verbosity
 	logger.GetLogger("raft").SetLevel(logger.ERROR)
-	logger.GetLogger("rsm").SetLevel(logger.WARNING)
-	logger.GetLogger("transport").SetLevel(logger.WARNING)
-	logger.GetLogger("grpc").SetLevel(logger.WARNING)
+	logger.GetLogger("rsm").SetLevel(logger.ERROR)
+	logger.GetLogger("transport").SetLevel(logger.ERROR)
+	logger.GetLogger("grpc").SetLevel(logger.ERROR)
+	logger.GetLogger("dragonboat").SetLevel(logger.ERROR)
 	// config for raft
 	rc := config.Config{
 		NodeID:             uint64(*nodeID),
@@ -210,7 +212,9 @@ func main() {
 	raftStopper.RunWorker(func() {
 		// this goroutine makes a linearizable read every 10 second. it returns the
 		// Count value maintained in IStateMachine. see datastore.go for details.
-		ticker := time.NewTicker(10 * time.Second)
+		const duration = 10
+		ticker := time.NewTicker(duration * time.Second)
+		var last_count uint64 = 0
 		for {
 			select {
 			case <-ticker.C:
@@ -220,13 +224,41 @@ func main() {
 				if err == nil {
 					var count uint64
 					count = binary.LittleEndian.Uint64(result)
-					fmt.Fprintf(os.Stdout, "count: %d\n", count)
+					this_count := count - last_count
+					last_count = count
+					fmt.Fprintf(os.Stdout, "duration: %d, count: %d, tps: %f\n", duration, this_count, float32(this_count)/float32(duration))
 				}
 			case <-raftStopper.ShouldStop():
 				return
 			}
 		}
 	})
+
+	time.Sleep(10 * time.Second)
+	for i := 0; i < *thread_num; i++ {
+		raftStopper.RunWorker(func() {
+
+			cs := nh.GetNoOPSession(exampleClusterID)
+			msg := "hello"
+			for {
+				select {
+				case <-raftStopper.ShouldStop():
+					return
+				default:
+					ctx, cancel := context.WithTimeout(context.Background(), 3*time.Second)
+					// make a proposal to update the IStateMachine instance
+					_, err := nh.SyncPropose(ctx, cs, []byte(msg))
+					cancel()
+					if err != nil {
+						fmt.Fprintf(os.Stderr, "SyncPropose returned error %v\n", err)
+						return
+					}
+				}
+			}
+		})
+	}
+
+	
 	raftStopper.RunWorker(func() {
 		// use a NO-OP client session here
 		// check the example in godoc to see how to use a regular client session
@@ -244,7 +276,7 @@ func main() {
 					makeMembershipChange(nh, cmd, addr, nodeID)
 				} else {
 					// input is a regular message need to be proposed
-					ctx, cancel := context.WithTimeout(context.Background(), 3*time.Second)
+					ctx, cancel := context.WithTimeout(context.Background(), 10*time.Second)
 					// make a proposal to update the IStateMachine instance
 					_, err := nh.SyncPropose(ctx, cs, []byte(msg))
 					cancel()
@@ -257,5 +289,6 @@ func main() {
 			}
 		}
 	})
+	
 	raftStopper.Wait()
 }
diff --git a/helloworld/statemachine.go b/helloworld/statemachine.go
index 1b9f6a4..0b31d72 100644
--- a/helloworld/statemachine.go
+++ b/helloworld/statemachine.go
@@ -16,7 +16,7 @@ package main
 
 import (
 	"encoding/binary"
-	"fmt"
+	//"fmt"
 	"io"
 	"io/ioutil"
 
@@ -58,8 +58,8 @@ func (s *ExampleStateMachine) Update(data []byte) uint64 {
 	// incoming update request. we also increase the counter by one to remember
 	// how many updates we have applied
 	s.Count++
-	fmt.Printf("from ExampleStateMachine.Update(), msg: %s, count:%d\n",
-		string(data), s.Count)
+	//fmt.Printf("from ExampleStateMachine.Update(), msg: %s, count:%d\n",
+	//	string(data), s.Count)
 	return uint64(len(data))
 }
 
```
There are 3 raft nodes, start as follow:
```
./helloworld -nodeid 1 -thread_num 400
```
```
./helloworld -nodeid 2
```
```
./helloworld -nodeid 3
```
As the code shows above, the node 1 will send proposal as many as possible.

**Comment by lni** [comment]
I've made your results hidden so it won't mislead other users. Please stop posting any such misleading benchmarks when you don't even understand how to use Dragonboat. 

After my fixes to your program, below is my results obtained on single socket E5-2696v4 with a single Intel P3700. I got close to 600,000 tps per second. Note that P3700 is **not** something new & shinning, it was released 5 years ago and already reached its EOL!   

on leader:

> leader here!
> duration: 10, count: 4697926, tps: 469792.593750
> duration: 10, count: 6153524, tps: 615352.375000
> duration: 10, count: 5873654, tps: 587365.375000
> duration: 10, count: 6142643, tps: 614264.312500
> duration: 10, count: 5884068, tps: 588406.812500

on two followers:

> duration: 10, count: 5072708, tps: 507270.812500
> duration: 10, count: 6166870, tps: 616687.000000
> duration: 10, count: 5842966, tps: 584296.625000
> duration: 10, count: 6157491, tps: 615749.125000
> duration: 10, count: 5886245, tps: 588624.500000

> duration: 10, count: 5525690, tps: 552569.000000
> duration: 10, count: 6196746, tps: 619674.625000
> duration: 10, count: 5832905, tps: 583290.500000
> duration: 10, count: 6143598, tps: 614359.812500
> duration: 10, count: 5903375, tps: 590337.500000

Also note that, your benchmark is completely meaningless, as it doesn't cause any real CPU load. Below is the output of top command, with %CPU in bold. What is the point running such benchmarks when each node only takes such small fraction of the available CPU cycles?  

> 12433 lni       20   0 6301580 1.444g  15268 R **441.4**  2.3   2:45.51 hello
> 13020 lni       20   0 5402588 1.372g  15216 S **141.4**  2.2   0:52.18 hello
> 12722 lni       20   0 5131308 1.373g  15372 S **137.9**  2.2   0:54.04 hello

In case you are still interested in braft, you may want to modify your program to use multiple Raft groups (say 36) to get the CPU fully loaded. Don't forget to increase the number of client threads.

Also note that Dragonboat's proposal is only considered as completed when it is fully **applied**, in braft, when I checked one year ago, it considers the proposal as completed once it is **committed**. There is HUGE difference here.**  

Your program has three major issues that can completely destroy the expected performance:

1. you set the program to generate snapshots every 10 updates. you couldn't see its happening because you switched off the log output. for most uses cases, your system is only suppose to generate a few snapshots each day for each raft group.

this is the biggest hit to performance.

2. when your program is spending all resources busy generating unwanted snapshots, obviously some proposals made by some of your 400 goroutines are going to fail. once it fails, it exit from the goroutine and you start to have less and less goroutines. 

3. proposals are made from an arbitrary node, the throughput will be higher when it is the leader by chance, but can be slower when it is a follower. this makes the results not reproducible during different runs.

**Comment by lni** [comment]
On the same hardware, it can easily hit over 1 million proposals per second using 1200 client goroutines:

leader:

> leader here!
> duration: 10, count: 9522115, tps: 952211.500000
> duration: 10, count: 11503876, tps: 1150387.625000
> duration: 10, count: 11489179, tps: 1148917.875000
> duration: 10, count: 12257170, tps: 1225717.000000

followers:

> duration: 10, count: 10411593, tps: 1041159.312500
> duration: 10, count: 11491221, tps: 1149122.125000
> duration: 10, count: 11516231, tps: 1151623.125000
> duration: 10, count: 12218634, tps: 1221863.375000
> 
> duration: 10, count: 11480276, tps: 1148027.625000
> duration: 10, count: 11459391, tps: 1145939.125000
> duration: 10, count: 11537762, tps: 1153776.250000
> duration: 10, count: 12226329, tps: 1222632.875000

top outout with %CPU in bold

> 14982 lni       20   0 7369104 1.371g  15096 S **997.3**  2.2   2:54.04 hello
> 15278 lni       20   0 5397852 1.276g  15424 S **163.8**  2.0   0:30.52 hello
> 15593 lni       20   0 5301276 1.320g  15332 S **162.8**  2.1   0:28.63 hello

Such results is still highly misleading as it gives people the impression that Dragonboat can only achieve 1.15 million tps. That is **NOT** true. Using the same hardware spec, but actually run it on 3 servers, Dragonboat can sustain at 9-10 million per second when there are 48 raft groups.

**Comment by lni** [comment]
Please also note that Dragonboat's performance has nothing to do with SATA or NVME disks. As long as you use Enterprise SATA SSDs, SATA disks such as Intel S3700 released almost 7 years ago can yield very good throughput results. Same for SATA disks like Intel S3710, Intel 320 and Micron 500DC. 

It is now pretty hard to buy SATA SSDs, I had to contact some vintage part vendors to get some second hand SATA Intel S3700/S3710. Will post results on such SATA SSDs soon.

**Comment by hnwyllmm** [comment]
thanks for your detail and patient explanation. And I am sorry for misunderstand.
Now I am looking for a raft library with high performance, the braft is one of candidate without enough performance.  After I saw the introduction of drangonboat, it attract me and I thought it is the best raft library. However, we should test it ourself before we use it. Testing can help me understand it.
I have asked you the settings and I got the code. However I cannot get the best performance. So I ask for your help.
Whatever, it is great reaching 600K even though you think it is dispiriting.
I will do more test follow your suggestion.
At last, could you post some demo code for performance. I think there are some other people like me who want to try it.
Thank you again!

**Comment by lni** [comment]
@hnwyllmm please feel free to run whatever test you want, but posting your throughput results measured when triggering hundreds of snapshots per second on a single Raft group is not helping your own evaluation. It is also quite disrespectful for people who are putting their own time into such a free & open source project. My recommendation is to carefully read the documents of _all libraries_ you are evaluating first - what's the point benchmarking all those libraries when you don't even understand them? 

You specifically mentioned that my results is only possible on NVME disks, I purchased a vintage Intel S3700 **SATA** SSD released 6.5 years ago. I will post results using your suggested program when the disk arrives. Other than that, I am not going to post any "performance demo".

**Comment by lni** [comment]
Below is the results on single socket E2696v4 + **almost 7 years** old Intel S3700 **SATA** SSD. I was running @hnwyllmm 's program with my above described fixes. 

using 400 client goroutines, output on leader:

> leader here!
> duration: 10, count: 1420627, tps: 142062.703125
> duration: 10, count: 1794129, tps: 179412.906250
> duration: 10, count: 1781426, tps: 178142.593750 

two followers:

> duration: 10, count: 1579027, tps: 157902.703125
> duration: 10, count: 1794361, tps: 179436.093750
> duration: 10, count: 1779194, tps: 177919.406250

> duration: 10, count: 1745556, tps: 174555.593750
> duration: 10, count: 1794000, tps: 179400.000000
> duration: 10, count: 1778226, tps: 177822.593750

using 1200 client goroutines, output from leader:

leader here!

> duration: 10, count: 3238307, tps: 323830.687500
> duration: 10, count: 4597729, tps: 459772.906250
> duration: 10, count: 4687732, tps: 468773.187500

followers:

> duration: 10, count: 3652750, tps: 365275.000000
> duration: 10, count: 4594198, tps: 459419.812500
> duration: 10, count: 4693358, tps: 469335.812500

> duration: 10, count: 4046626, tps: 404662.593750
> duration: 10, count: 4602748, tps: 460274.812500
> duration: 10, count: 4695915, tps: 469591.500000

**Comment by hnwyllmm** [comment]
So, the performance of disk will impack the result?
below is the perforamce testing result of our disk. I think it is the worst disk on the world.
```
start bench small data
                    avg value size 100 qps 469
start bench large data
            avg value size 100000 qps 88
```

**Comment by lni** [comment]
@hnwyllmm if you have concerns about your disk performance, or have questions on using dragonboat, please feel free to ask, what is the point posting your highly misleading results again? 

Like all consensus libraries, Dragonboat's throughput is highly dependent on fsync() performance, for which you can measure using the pg_test_fsync tool shipped with PostgreSQL. 

You seems to be using a disk with fsync() latency of 8-10ms, that is **NOT** an SSD suitable for server use. Also, other than the 3 major issues I pointed out in your highly misleading program, another huge impact on its throughput is the fact that all 400 goroutines start the proposals at the exact same time, they will thus complete at the same time, then keep repeating this forever. There is no other requests in between (between the start/completion of those 400 proposals), huge CPU & disk resources are wasted. 

Note that, almost all issues I pointed out in this thread has nothing to do with any consensus library, they are mostly general issues in high performance back end systems. I don't think you are ready to benchmark such high performance systems yet. Please stop posting your highly misleading results.

**Comment by hnwyllmm** [comment]
I don't want to misleading anyone. And I think no one will be misled as the result is so good you post. All I do is just to tell you what result I got and if there are something wrong in my test. One million is a very fascinate number and I have the disire to display it on my testing environment and I am working on it.
But I don't agree with the point: 400 goroutines start the proposals at the exat same time and complete at the same time. I have tried 200+100+100 model and the result is similar.
At last, I will never post my result again and give up testing the high performance system.

**Comment by lni** [comment]
@hnwyllmm 

your numbers are totally misleading for reasons listed below - 

1. you mentioned in your post that "with snapshot period 1000 seconds", Dragonboat doesn't even support snapshotting by time interval, how could you set such "snapshot period"? As clearly documented in both the godoc and in the example program, if you set SnapshotEntries to 1000, it means a snapshot is going to be captured for each 1000 updates. by doing that, you are still generating numerous snapshots for each of your sampling period of 10 seconds. 

2. results on different types of SSDs have been provided, including SATA SSD under your explicit request. All hardware specs have been made clear. You have been keep posting highly misleading results without any disclosure on hardware spec, e.g. what is the brand and model of your disk? 

3. Dragonboat is a multi-group Raft, see the README file. I am working with multiple users, they run thousands of Raft groups on each server. Other than the Drummer component used in test which handles probably a few hundred writes per second, I have never ever had any real-world use case for single group Raft. It has been mentioned in this thread that using a single Raft group to measure the performance of multi-group Raft library is misleading. yet you choose to keep posting results without even listening to any of these. 

4. you are testing a write only work load in which a single read operation is issued every 10 second. there is no such real-world workload. If you look at the benchmark results provided on README, all throughput results are provided as mixed-IO results with different read-to-write ratios. 

As a summary - you misconfigured your system to generate way too many unwanted snapshots, you choose to benchmark a multi-group raft library using a single raft group, you tested it against a write only workload not realistic at all in real world. all these were done on some random unknown hardware no one knows what is the spec, the only hardware info that I can _guess_ is that the disk takes 8ms to complete a fsync() when an enterprise SATA SSD usually takes less than 200us, while a consumer grade SATA SSD such as Samsung 850 EVO usually takes 2-3ms. You tell me how this is not wasting time for everyone? 

This is my last reply in this totally meaningless thread.
