### ISSUE TITLE
IStateMachine thread-safe?

### ISSUE THREAD

**Issue by Cloud33** [lni/dragonboat#231]
It may be a very simple question. Is `IStateMachine` thread safe? If it is a KV memory database, do you need to add `RLock`?

**Comment by lni** [comment]
It is internally locked, so you don't need to use RLock inside IStateMachine. 

In case you don't want such behaviour, feel free to use IConcurrentStateMachine instead which gives your IConcurrentStateMachine full control. 

Please also read the godocs of those interfaces, the above described details are well documented there.
