### ISSUE TITLE
Gossip how to use?

### ISSUE THREAD

**Issue by xkeyideal** [lni/dragonboat#233]
1. first use set RaftAddress(can't change) start the raft cluster, then print NodeHostID to generate `initialMembers`, second change use Gossip start the raft cluster, the error `AddressByNodeHostID changed`

2. first use nodeId generate NodeHostID  for `initialMembers` and set `AddressByNodeHostID=true`, but the `dragonboat` will random generate NodeHostID, can't use `initialMembers` paramters as NodeHostID, so the raft cluster can't start.

3. first start use `2`, then changed `initialMembers` use the `dragonboat` random generate NodeHostID, the raft cluster also can't start, the errrors are:
  `"msg": "inconsistent node list, bootstrap map[11772876509704:nhid-11772876509704 11772876509705:nhid-11772876509705 11772876509706:nhid-11772876509706 11772876509707:nhid-11772876509707 11772876509708:nhid-11772876509708], incoming map[11772876509704:nhid-15018748226251869746 11772876509705:nhid-778555109353804057 11772876509706:nhid-11205450167128831891 11772876509707:nhid-6871943544045681538 11772876509708:nhid-7080250968060701619]"` 

  `"msg": "bootstrap info validation failed, [00001:09708], map[11772876509704:nhid-11772876509704 11772876509705:nhid-11772876509705 11772876509706:nhid-11772876509706 11772876509707:nhid-11772876509707 11772876509708:nhid-11772876509708], false, map[11772876509704:nhid-15018748226251869746 11772876509705:nhid-778555109353804057 11772876509706:nhid-11205450167128831891 11772876509707:nhid-6871943544045681538 11772876509708:nhid-7080250968060701619], false"`

So I can't understand how to use the Gossip config start the raft cluster?

**Comment by xkeyideal** [comment]
And why v3.3.5 remove `transport/gossip_logger.go` file, the gossip log will print by os.StdErr, and can't set the log level

The next version will add the feature?

**Comment by xkeyideal** [comment]
And the next version can provide a test node ready buildin API, now user just loop try test the node ready for the error `request dropped as the cluster is not ready` 

I see your `nodehost_test.go` file test codes test node ready, and write it.
```go
func (s *Storage) nodeReady(clusterIds []uint64, ch chan<- struct{}) {
	set := make(map[uint64]struct{})
	for _, clusterId := range clusterIds {
		set[clusterId] = struct{}{}
	}

	cmd := command.NewPutCommand(constant.ColumnFamilyDefault, []byte("__raft_node_ready_"), []byte("1"))
	b, _ := command.EncodeCmd(cmd)

	for _, clusterId := range clusterIds {
		session := s.csMap[clusterId]
		// 等待每个clusterId选主完毕
		for {
			ctx, cancel := context.WithTimeout(context.Background(), 3*time.Second)
			_, err := s.nh.SyncPropose(ctx, session, b)
			cancel()
			if err == dragonboat.ErrTimeout || err == dragonboat.ErrClusterNotReady {
				//log.Println(s.target, err)
				time.Sleep(100 * time.Millisecond)
				continue
			}

			if err == nil {
				//log.Println("v ...interface{}", s.target, clusterId, s.nodeId)
				delete(set, clusterId)
				break
			}
		}

		if len(set) == 0 {
			ch <- struct{}{}
			return
		}
	}
}
```

By my test, the local host clusters be ready status need 2-3 seconds.
so I hope dragonboat framework encapsulate the API for users.

**Comment by xkeyideal** [comment]
I had used ExpertConfig.TestNodeHostID solve the problem.

**Comment by lni** [comment]
That TestNodeHostID parameter is provided for testing, you are misusing it. I think it will be eventually removed. 

Please see the godoc of NodeHostConfig to see how to use the Gossip feature. 

https://pkg.go.dev/github.com/lni/dragonboat/v3@v3.3.5/config

**Comment by xkeyideal** [comment]
> That TestNodeHostID parameter is provided for testing, you are misusing it. I think it will be eventually removed.
> 
> Please see the godoc of NodeHostConfig to see how to use the Gossip feature.
> 
> https://pkg.go.dev/github.com/lni/dragonboat/v3@v3.3.5/config

I attempt misusing TestNodeHostID, but the NodeHostConfig can't set the nhid by user, I must startup my application then know the nhid, so this did not meet my expectations. And my application need initial project configuration after raft startup, so I must know other raft machine's nhid, so it can't be manually configured after program startup. 

My requirement is to know nhid explicitly before the program startup.

And Covid-19 in Shanghai is serious,  wish you all the best

**Comment by xkeyideal** [comment]
> And the next version can provide a test node ready buildin API, now user just loop try test the node ready for the error `request dropped as the cluster is not ready`
> 
> I see your `nodehost_test.go` file test codes test node ready, and write it.
> 
> ```go
> func (s *Storage) nodeReady(clusterIds []uint64, ch chan<- struct{}) {
> 	set := make(map[uint64]struct{})
> 	for _, clusterId := range clusterIds {
> 		set[clusterId] = struct{}{}
> 	}
> 
> 	cmd := command.NewPutCommand(constant.ColumnFamilyDefault, []byte("__raft_node_ready_"), []byte("1"))
> 	b, _ := command.EncodeCmd(cmd)
> 
> 	for _, clusterId := range clusterIds {
> 		session := s.csMap[clusterId]
> 		// 等待每个clusterId选主完毕
> 		for {
> 			ctx, cancel := context.WithTimeout(context.Background(), 3*time.Second)
> 			_, err := s.nh.SyncPropose(ctx, session, b)
> 			cancel()
> 			if err == dragonboat.ErrTimeout || err == dragonboat.ErrClusterNotReady {
> 				//log.Println(s.target, err)
> 				time.Sleep(100 * time.Millisecond)
> 				continue
> 			}
> 
> 			if err == nil {
> 				//log.Println("v ...interface{}", s.target, clusterId, s.nodeId)
> 				delete(set, clusterId)
> 				break
> 			}
> 		}
> 
> 		if len(set) == 0 {
> 			ch <- struct{}{}
> 			return
> 		}
> 	}
> }
> ```
> 
> By my test, the local host clusters be ready status need 2-3 seconds. so I hope dragonboat framework encapsulate the API for users.

Please see the suggestion which dragonboat support API for check the raft node clusters are all ready?

**Comment by xkeyideal** [comment]
I see the NodeHostConfig and sourcecode again.

```go
// To use these machines, first enable the NodeHostConfig.AddressByNodeHostID
// field and start the NodeHost instances. The NodeHostID value of each
// NodeHost instance can be obtained by calling NodeHost.ID(). Let's say they
// are
//
// "nhid-xxxxx",
// "nhid-yyyyy",
// "nhid-zzzzz".
//
// All these NodeHostID are fixed, they will never change after reboots.
//
// When starting Raft nodes or requesting new nodes to be added, use the above
// mentioned NodeHostID values as the target parameters (which are of the
// Target type). Let's say we want to start a Raft Node as a part of a three
// replicas Raft cluster, the initialMembers parameter of the StartCluster
// method can be set to
//
// initialMembers := map[uint64]Target {
// 	 1: "nhid-xxxxx",
//   2: "nhid-yyyyy",
//   3: "nhid-zzzzz",
// }
```

```go
func (nh *NodeHost) loadNodeHostID() error {
	if nh.nhConfig.Expert.TestNodeHostID == 0 {
		nhid, err := nh.env.LoadNodeHostID()
		if err != nil {
			return err
		}
		nh.id = nhid
	} else {
		nhid, err := id.NewNodeHostID(nh.nhConfig.Expert.TestNodeHostID)
		if err != nil {
			return err
		}
		nh.id = nhid
		nh.env.SetNodeHostID(nh.id)
	}
	return nil
}

// LoadNodeHostID loads the NodeHost ID value from the ID file. A new ID file
// will be created with a randomly assigned NodeHostID when running for the
// first time.
func (env *Env) LoadNodeHostID() (*id.NodeHostID, error) {
	dir, _ := env.getDataDirs()
	nhID := id.NewRandomNodeHostID()
	if fileutil.HasFlagFile(dir, idFilename, env.fs) {
		if err := fileutil.GetFlagFileContent(dir,
			idFilename, nhID, env.fs); err != nil {
			return nil, err
		}
	} else {
		if err := fileutil.CreateFlagFile(dir,
			idFilename, nhID, env.fs); err != nil {
			return nil, err
		}
	}
	env.nhid = nhID
	return nhID, nil
}
```

The source code NodeHostID is created with a randomly, I need a permanent and user can set(just first startup and never change after reboots), I have tested many solutions and can't achieve this requirement. So I only use TestNodeHostID
