### ISSUE TITLE
Not an issue, just a question

### ISSUE THREAD

**Issue by morphar** [lni/dragonboat#239]
Hi @lni :)
Thank you for sharing this project, I love it! Multi-raft is exactly what I needed 👍 

I am currently using v3.3.5 for a project I'm building.
I was just wondering how stable and feature complete `master` is and how far away a v3.4.0 is?

It's not to rush you **at all** - I am just trying to decide, whether I should stick with v3.3.5 or use the `master` branch instead.

**Comment by lni** [comment]
I'd recommend to use the latest released version which is v3.3.5. 

As the dev branch of the project, there are a few known issues on the master branch. I'd expect v3.4.0 to be released once all of them are addressed, hopefully in a few weeks.

**Comment by morphar** [comment]
Super 👍 Thank you @lni :)

**Comment by lni** [comment]
@morphar 

In case you are interested in what new v3.4 features are not available in v3.3, please have a look at the CHANGELOG.md.

**Comment by morphar** [comment]
Thanks @lni 👍 I read that file and thought it would be nice with Gossip, but I will just use v3.3 and wait for v3.4 before implementing Gossip.

**Comment by lni** [comment]
@morphar gossip was released as a part of v3.3, so you won't miss that. The only new feature in v3.4 that you won't get in v3.3 is the pre-vote support, which from my understanding is not super useful.

**Comment by morphar** [comment]
Nice 👍 I will try to get that working then. Thanks @lni 👍
