### ISSUE TITLE
Question: Horizontal Scalability?

### ISSUE THREAD

**Issue by touhonoob** [lni/dragonboat#243]
Can horizontal scalability be achieved with dragonboat's multi-raft implementation?
Is there any configuration that needs to be made for this particular feature?
Thanks a lot!

**Comment by lni** [comment]
Yes. You can horizontally scale to use many different raft groups (each called a raft cluster) on many machines, you can increase the number of such raft groups/machines in your deployment when necessary. 

Your dragonboat based program should have code to manage the creation of such raft groups and determines where to put those replicas (called raft nodes in dragonboat).
