### ISSUE TITLE
Unknown Panic

### ISSUE THREAD

**Issue by siennathesane** [lni/dragonboat#250]
Hi, I wanted to understand why this bit of code might panic.

https://github.com/lni/dragonboat/blob/cdd710b5d50e2b0d51b163a934d80ae3d90ff311/logger/logger.go#L62-L64

I'm getting very strange behavior that I'm not sure I understand. I have a test suite that idempotently test different node host wrappers. Each test creates a node host which uses a `vfs.MemFS`, random port, a custom logger, and is completely isolated from a node host in a different test. When I run a single test, the test works as intended. However, when I run the test suite, all the node host instances throw this panic.

Since each node host is completely independent of the other, I'm not sure why it's panicking, or even why it should cause a panic. Would you be able to explain why it panics and how I should avoid it?

**Comment by lni** [comment]
It seems to me that you are probably calling SetLoggerFactory() multiple times. 

The godoc of that function should have been more specific on this limitation.

**Comment by siennathesane** [comment]
Yeah, eventually I was able to figure it out - I just didn't realise this was a top level function. I'll submit a PR.
