### ISSUE TITLE
how about put original protobuf files into the repo?

### ISSUE THREAD

**Issue by cjl3080434008** [lni/dragonboat#263]
I'm sorry about that I had not found the original protobuf files in the repo, so can you please put them into it.  If I had missed something please correct me thanks.

**Comment by lni** [comment]
dragonboat no longer uses protobuf / gogoprotobuf anymore. 

you can see a few types in the raftpb folder that still carry some protobuf traits, they are actually the result of protobuf + colfer + hand written code. please just consider them as hand written.
