### ISSUE TITLE
do u have an example of automatically adding node ips?

### ISSUE THREAD

**Issue by kolinfluence** [lni/dragonboat#272]
do u have an example of automatically adding node ips?
it seems all ip data is manually entered. how to auto add?

**Comment by lni** [comment]
I don't quite understand what do you mean by adding node ips. Do you want to assign new IPs to existing nodes, or you want to add new nodes with never seen before IP values?

**Comment by kolinfluence** [comment]
assigning new ip to nodes. never seen before ip values. and how to remove them?

**Comment by lni** [comment]
Sorry but I still don't quite get what you want. 

Assigning new IPs to your nodes has nothing to do with your consensus library.

**Comment by kolinfluence** [comment]
how to dynamically add nodes and remove them?

**Comment by lni** [comment]
https://github.com/lni/dragonboat-example/tree/master/helloworld

the link above contains example code and step by step description.
