### ISSUE TITLE
need pub sub features of redis or fastest pub sub implementation u can think of.

### ISSUE THREAD

**Issue by hiqsociety** [lni/dragonboat#275]
need pub sub features of redis or fastest pub sub implementation u can think of in terms of latency, minimal data transfers overhead, txn per second + highest throughput

does dragonboat have an example or an existing solution?

i saw some comments over others using nats.io which is what i am trying to avoid and hope to make one better with dragonboat.

any suggestions on where shld i start or is there a boilerplate that is easy to work with for now?

**Comment by lni** [comment]
dragonboat is not a pub sub system. please feel free to build your own if you want.
