### ISSUE TITLE
purpose of multi raft group

### ISSUE THREAD

**Issue by kolinfluence** [lni/dragonboat#276]
my understanding of raft has been 1 raft group

what's the purpose of multiple raft group?

what's the major advantage. and why thousands of raft group when 1 will suffice?

**Comment by lni** [comment]
please check cockroachdb or tidb's design docs, or read the spanner paper. they gave detailed explanations on that. 

as a consensus library, dragonboat support unlimited number of shards, how many shards your application should be using is up to you. we don't have any limit on that.
