### ISSUE TITLE
how to make delta snapshot

### ISSUE THREAD

**Issue by gensmusic** [lni/dragonboat#28]
we config SnapshotEntries 10000, and a node restarted, 5 minites later it restarted and just 11000 late from master. the node still needs a full snapshot to recover. let's say the full snapshot is about 10m entries which is too big.
Is there any way to notify master to generate a smaller snapshot by telling it some extra info ?

**Comment by lni** [comment]
Please note that snapshot is not for such incremental updates, Raft logs are used for such incremental updates. 

When your SnapshotEntries is set to 10,000, you are basically telling the Dragonboat library that "sending 10,000 log entries to a follower is more expensive than sending the snapshot". This seems to be not true based on your description above - as you mentioned that sending a snapshot is way more expensive. In short, for your use case, you set the SnapshotEntries value way too small.

Please also have a look at the CompactionOverhead parameter, I usually set it to be 50% of the SnapshotEntries.
