### ISSUE TITLE
reference scylladb

### ISSUE THREAD

**Issue by kolinfluence** [lni/dragonboat#281]
if you can make node addition with replication factor of 3 or 5 like scylladb adding and deleting nodes.
i think this will be a complete raft solution.

as for backend kv storage, can use terarkdb / pebble. for raft logs, tan.

then this will be perfect. i can contribute code if u are willing to help do the RF 3/5 thing example.

and then u can focus on Tan log coz that area i cant help.

we can make it into a really useful raft application with replication factors.

**Comment by lni** [comment]
> if you can make node addition with replication factor of 3 or 5 like scylladb adding and deleting nodes.
> i think this will be a complete raft solution.

this is supported since day one. 

> and then u can focus on Tan log coz that area i cant help.

this has been in production for many years.

**Comment by lni** [comment]
I saw about 10 issues opened at the same time by your account and by [hiqsociety](https://github.com/hiqsociety), are you two related, working on the same project? 

After reading & addressing your questions, I have the feeling that you didn't read the dragonboat docs at all. Please read the docs before raising any issues. You should also spend your time to read the raft paper if you want to use raft. 
  
Thanks.
