### ISSUE TITLE
what's the limit of raft nodes?

### ISSUE THREAD

**Issue by kolinfluence** [lni/dragonboat#282]
1. how many raft nodes can i add? 50000? just curious.
2. does it mean all 50000 will store duplicated data or is there a way to do Replication Factor = 5 or 3 so that only 3 / 5 copies are stored?

**Comment by lni** [comment]
1. you can have unlimited number of nodes. it is only limited by the resources you have. 
2. dragonboat uses majority quorum. use 5 replicas for your shard and you get replication factor of 5 and quorum of 3.
