### ISSUE TITLE
thx for prompt reply. I finished reading the doc.

### ISSUE THREAD

**Issue by kolinfluence** [lni/dragonboat#284]
1. how can i specify the majority quorum? is the initial starting addresses specifying the number of replication factor?
actually it's more like how do i specify the replication factor? i would like to do RF = 5, please mention how to set this number.

2. possible to mention a date on version 4.0? it sounds very exciting and hope to see it happen.

**Comment by kolinfluence** [comment]
i hv only read this doc
https://pkg.go.dev/github.com/lni/dragonboat?utm_source=godoc

is there another doc u talking about?

**Comment by lni** [comment]
If you are not sure how to set quorum size, you are not ready for writing any raft based application.  Please read the raft paper and dragonboat's examples first to get yourself familiar with the raft protocol.  

https://github.com/lni/dragonboat-example

all features of the v4.0 is already in the master branch. as an API breaking release, it will be released when I finish all API changes.
