### ISSUE TITLE
last question just for clarification

### ISSUE THREAD

**Issue by kolinfluence** [lni/dragonboat#285]
i understand quorum but my mind is rigitly fixed by the way scylladb and tidb, cockroachdb etc implement their "quorum" settings based on RF (replication factor)

i've seen the code too and i understand the "raft group" now more.
what i am asking is:
if i add more nodes to a raft group. if from 3 (needing 2 for quorum) to 5 (which means need 3 for quorum), then i cut back to 2 servers by removing nodes of the raft group, will it still work with 2 for quorum or i need it to be 3 back? means i can add more nodes to raft group but removing it, does it affect "quorum"?

p.s. : i dont see a place where i can put "replication factor" <- for other DBs, the RF value determines the quorum of N members.

pls help clarify my doubts. thx

**Comment by lni** [comment]
Please read the raft paper. Dragonboat is a direct implementation of the raft paper. It doesn't change anything specified in the paper.

**Comment by kevburnsjr** [comment]
ScylladDB, CockroachDB and TiDB are databases. Dragonboat is not a database. It is a raft library.
If you wanted to create a database using Dragonboat, you might:

1) Start a `NodeHost` on each of your nodes (suppose you have 16).
2) Use a `consistent hashing` algorithm to divide your keyspace into 256 `partition`s
3) Create one `shard` in Dragonboat for each partition
4) Start 3 (or 5) `replica`s for each shard distributed evenly among your 16 nodehosts

In this way, each node would host 48 (or 80) replicas.
Each shard would represent a durable, linearizable partition of the dataset.
Multi-raft can be used in this way to manage shards in a distributed dataset.
Starting the replicas and deciding how many to create (RF) is a task left to the user.

Here is an example of a distributed hash set built with LMDB and Dragonboat that might help put the technology into context.
https://github.com/logbn/shackle

**Comment by kolinfluence** [comment]
@kevburnsjr

the problem is i cant seem to find the starting "replica" value to define in the code / doc of dragonboat.
do u know which example clearly shows the "initial num of replica value" (replication factor)?

this "quorum" is fixed depending on "initial num of replica value" right? so once i set this initial num of replica value, the quorum will be based to this value and immutable right?

**Comment by kevburnsjr** [comment]
Correct.

Quorum is a mathematical concept defined as 
```
quorum = floor(n/2) + 1
```

Some eventually consistent databases like Riak and CouchDB (iirc) support varying levels of write durability where you can select per request whether to consider a write as successful after being fsynced to disk on 1, quorum, or all nodes. That is not supported by Dragonboat. You would need to implement that separately.

The number of replicas you create and join to the cluster is the resulting replica factor. If you want that to be a setting that you can change it would be a setting in your code.

**Comment by kolinfluence** [comment]
@kevburnsjr ok. thx for clarifying

do u know where i can find this
> 4. Start 3 (or 5) replicas for each shard distributed evenly among your 16 nodehosts

how to find out this code segment in example? is this automatic distribution or i need to do something special?

**Comment by kevburnsjr** [comment]
You need to write the code that decides where to place the replicas (see TiDB's Placement Driver). You also need to write the code that rebalances the replicas when nodes are added / removed from the cluster. Shackle is basic. The manifest is static. It doesn't support scaling or healing.

See [initializeManifest](https://github.com/logbn/shackle/blob/5a7e77fcee72fb42448585052d080b784e0505ff/cluster/host.go#L806)
And [startNodes](https://github.com/logbn/shackle/blob/5a7e77fcee72fb42448585052d080b784e0505ff/cluster/host.go#L181)
And [example config](https://github.com/logbn/shackle/blob/5a7e77fcee72fb42448585052d080b784e0505ff/_example/local_3x2/config.1.yml#L40)
