### ISSUE TITLE
any simple things i can do to help make v4 complete?

### ISSUE THREAD

**Issue by kolinfluence** [lni/dragonboat#286]
any simple things i can do to help make v4 complete?
so as to be consistent with api changes etc.

sorry about the questions asked because i was confused at this part with the naming.
ClusterID/NodeID has been renamed as ShardID/ReplicaID.

seeing this in v4 changelog i understand better now.

p.s. : is there a date to when v4 will be mainstream?

**Comment by lni** [comment]
The naming is a big reason for the v4 breaking changes. The plan is to cleanup all names and update all docs to make sure it is consistent. I also have the feeling that the APIs are getting too complicated. Will review it to simplify things a little bit. 

After using the library for a few weeks/months, it will be useful if you can send in some concrete feedbacks, like "this is confusing", "this is too complicated, we can simplify it this way..." kind of recommendations. 

thanks.

**Comment by kolinfluence** [comment]
my understanding of raft is based upon long usage of tidb and scylladb

i understand scylladb more.

BUT I suggest u use the terminologies / methods and naming conventions with tidb because their "way" is "better"

i believe this raft is better implemented in the style of scylladb (minimal, simple 1 binary file)
quorum style follows scylla

but direction wise using tidb's implementation with range style clustering method (in future or allow us to implement ourselves)

following all conventions above is easier for others to understand as their docs are comprehensive and inter-related in deployment "strategies" for real world usage.

having said so i suggest u read through both their docs in their implementation strategies and naming conventions

**Comment by lni** [comment]
> BUT I suggest u use the terminologies / methods and naming conventions with tidb because their "way" is "better"

Sorry but there is no reason to believe that tidb is better in that regard. 

As a direct implementation of the Raft protocol, it is much better to follow any conventions used in the raft paper. If you check the internal/raft package which contains that implementation, it already follows all raft paper conventions. 

More re-alignments will be made for other packages to follow the conventions of the raft paper.   

> having said so i suggest u read through both their docs in their implementation strategies and naming conventions

I am not sure what implementation strategies you are talking about, but TIDB's raft implementation is just a rust re-implementation based on etcd raft.  Also note that I don't want Dragonboat to be database centric - there is a much bigger world outside databases.

**Comment by kolinfluence** [comment]
it's difficult not to associate raft with any other db implementations and mostly i think it's unavoidable if people look into raft and definitely will go onto scylla / tidb sooner or later.

the consistency of "raft" implementation and naming with cassandra / tidb is very straight forward.

i agree that it's not just db we shld be looking at but in that case it's best if you just finalize v4 so we can just use it then.

ClusterID/NodeID has been renamed as ShardID/ReplicaID. <- this is totally strange.

1 raft group is 1 raft cluster? 
multi raft group is means multi raft clusters?

```
1 raft cluster has multiple nodes.
each node can have different shards
each shard has different replicas

each replica host a set of data entries. (in kv terms)
```

i think u shld refrain from using "raft group" but as raft cluster. correct me if i'm wrong but raft group kind of seems confusing. not sure if others think so.

(if u use tidb, then "region" will need to be developed independently, but that's another thing not related to this raft implementation)

is this fine?

**Comment by kolinfluence** [comment]
it's beyond my imagination if v4 is not out and people can develop any serious app into this when naming is not standardize.
pls help standardize this asap. maybe we can just standardize in 2 days. i'm mentioning in reference to scylla and tidb. it's straightforward.

**Comment by kolinfluence** [comment]
after i read through the example and having said what i've already suggested, i think u must update and conclude this asap. it's too difficult to read the examples when they are defined / stated in those manners.

pls check and revert asap.

```
1 raft cluster has multiple nodes.
each node can have different shards
each shard has different replicas

each replica host a set of data entries. (in kv terms)
```

this is the way. no compromise.

**Comment by ghost** [comment]
Ref: https://raft.github.io/raft.pdf

If names are being changed, shard ID should actually be member ID. Reason being: nowhere in the raft paper is "shard" or "node" used. The terms "leader", "candidate", "follower", and "member" are used throughout the paper.

The term "shard" or verb "sharding" has a lot of history rooted in database, but raft is not limited to database use.

**Comment by kolinfluence** [comment]
u guys may want to use a few terms but what i've mentioned is mainstream naming and thoughts based on tidb / scylladb.

just explain in greater detail do for newcomers in.

i'm going to use scylladb for the moment until this is standardized. keep up the good work!

**Comment by kevburnsjr** [comment]
> i'm going to use scylladb for the moment until this is standardized.

That sounds like a wise decision. ScyllaDB is a mature and robust database with excellent documentation, cloud hosting options and enterprise support contracts. I'm sure they'd be happy to have you as a customer.

**Comment by ghost** [comment]
> what i've mentioned is mainstream naming and thoughts based on tidb / scylladb

What you mentioned are databases. Dragonboat is not a database, but instead a multi-RAFT implementation. This is not a toolkit for making databases, despite that being the obvious use-case.

Raft is a well established consensus protocol that is based on Paxos, not to be confused with Paxos. The way elections work and snapshotting works are major things setting Raft apart.

Newcomers really need a lot of knowledge about consensus to use this type of library. There is a single-raft library called hashicorp/raft that is a lot easier to learn and use; but for all of it's convenience, it really does a disservice to the end user who might not understand that a single raft group will forever be limited in scale.
