### ISSUE TITLE
Tan may havn't implement old entry rewrite

### ISSUE THREAD

**Issue by flashmouse** [lni/dragonboat#288]
Hi I just check the code with commitid 023bafb8e648934a8f16b98ff58d91b743358687, seems Tan now only support delete file  all entries  are removed,  so in such scenario that 2 nodes (called A and B)write raft log to the same db instance, A keep write new log persisted to fileNum 1~10, B stopped write for long time  and keep its last state entry in fileNum 1,  then fileNum 1 couldn't be deleted.

Does the problem mentenioned above exists or my understanding is wrong? If that's true then how could we handle this or just think it's acceptable? I notice LogDb has method `CompactEntriesTo` but seems for now it does nothing, maybe this method is designed to resolve this?

thx..

**Comment by lni** [comment]
> then fileNum 1 couldn't be deleted.

all nodes should do checkpoint periodically. that solves the problem you described above - when node B makes a checkpoint, a state record will also be saved. 

note that for disk based state machines, producing & storing such a checkpoint is extremely cheap (save several Kbytes). for in memory state machines, it is more expensive to produce checkpoints, but you have to do that regularly anyway to avoid replaying too many logs (thus unreasonably long recovery time) when you restart. 

> I notice LogDb has method CompactEntriesTo but seems for now it does nothing

CompactEntriesTo doesn't remove entries, it reclaims space used by those already removed entries (similar to compaction in a LSM). RemoveEntriesTo is the method for removing entries. Tan's CompactEntriesTo doesn't do anything as it doesn't need a separate procedure for reclaiming disk space.

**Comment by flashmouse** [comment]
that seems what I need, does dragonboat have any plan implement that? or we may do that ourselves

**Comment by lni** [comment]
What I described above are already in Dragonboat from day one.
