### ISSUE TITLE
proposal: binding address and advertise address

### ISSUE THREAD

**Issue by gensmusic** [lni/dragonboat#30]
When using the optional Master server, NodeHost periodically sends its details to the Master server. There is only one RaftAddress right now. We use it both for binding address and advertise address. there are cases we cannot use the RaftAddress as the binding address, e.g. when private/public address mapping is involved.
 
Is there any chance to add an advertise address?
if advertise address is not set, nothing changed.
if advertise address is set, use advertise address for identification.

**Comment by lni** [comment]
> there are cases we cannot use the RaftAddress as the binding address such as in docker 

I think what you are trying to suggest is that when using the Master server component, which is optional, the RaftAddress can't be used as the binding address where there is private/public address mapping. e.g. a nodehost binds to the private address 10.0.0.1:80 when it is accessible by a remote program from a public address say node1.mydomain.com:8080. 

This has nothing to do with docker as you can have similar setup in other environment while docker users may choose to use the host network driver to avoid such mapping. 

For most users, when they are not using the optional Master server, there is actually nothing for a NodeHost to advertise. The above mapping is managed by user programs - RaftAddress can be set to the private address so the NodeHost listens on it. All Raft member addresses (specified when you start cluster or do membership changes) should be using the public addresses. With the correct docker published port configuration, such setup should work fine in docker. 
 
> Is there any chance to add an advetise address?

I agree that when using the optional Master server component, the address used to identify the NodeHost should be the public address and it should be explicitly separated from the bind address. 

Considering to add a bind address to the config and keep RaftAddress as the identification.

**Comment by gensmusic** [comment]
great, also, in my case, docker using host network is not allowed by some security policy in my company.

**Comment by lni** [comment]
I've edited the original post to better describe the issue.

**Comment by lni** [comment]
@gensmusic this issue has been resolved in https://github.com/lni/dragonboat/commit/968d735048ab0f909dca9835e1d048394c62ccc6

please note that the Master server support will be reworked in the major release, details in https://github.com/lni/dragonboat/issues/32.

**Comment by gensmusic** [comment]
cool

**Comment by lni** [comment]
@gensmusic please try the version in the Master branch and let me know if you see anything strange. thanks!
