### ISSUE TITLE
Can the configuration set the frequency of writing logs to disk?

### ISSUE THREAD

**Issue by hyk1st** [lni/dragonboat#305]
Configuration can set the frequency of writing logs to disk, I feel that each write logs are stored performance overhead

**Comment by hyk1st** [comment]
Can the configuration set the frequency of writing logs to disk? I feel that the performance overhead of saving every write log is high.

**Comment by lni** [comment]
Without saving the log of each proposal to the disk & call fsync, you'd be facing the risk of losing data. 

Yes, it is a performance hit, but there is really nothing you can do when the whole purpose is to avoid losing data (that is why people maintain multiple replicas using protocols like Raft/Paxos). The good news is that with recent advances in SSD performance, especially those enterprise SSD, such performance drop is limited. I don't have any concrete numbers now, but I'd be willing to bet that we are talking about 25% write throughput drop when using fsync writes on P5510 class of SSDs.

**Comment by hyk1st** [comment]
Thanks for the answer, I feel it would be cool to leave the balance of consistency and performance to the user,haha

**Comment by lni** [comment]
it is more like - 

user A: I want a reliable system
user B: use library X
user A:  it is cool, but it is going to slow down my processing
user B: but you get the reliability you want and pretty good scalability
user A: I have to disable X to maximize my throughput
user B: do you still want a reliable system?
user A: maybe not anymore

:)
