### ISSUE TITLE
where is the doc on how the mechanics of "tan" log work?

### ISSUE THREAD

**Issue by kolinfluence** [lni/dragonboat#306]
where is the doc on how the mechanics of "tan" log work?

**Comment by lni** [comment]
There is no concrete docs for that, the implementation itself is pretty straight forward. 

Please feel free to read the code and ask questions whenever you want.

**Comment by kolinfluence** [comment]
@lni can you pls write a simple 2 paragraphs with a "table" in text how the data definition is stored?

something like this? just something simple for people to digest
https://blog.csdn.net/ByteDanceTech/article/details/129964969?ydreferer=aHR0cHM6Ly93d3cuZ29vZ2xlLmNvbS8%3D

it's definitely simple to you but high performance stuff is never simple.

**Comment by lni** [comment]
sorry, but such duplicated info (everything already in the code) is expensive to maintain and quite often it becomes inconsistent soon after it is written.
