### ISSUE TITLE
into high performance and was thinking about this "tan" log replacing wal inside rocksdb

### ISSUE THREAD

**Issue by kolinfluence** [lni/dragonboat#308]
1. can i disable WAL since tan is already used for replication of rocksdb?
2. why not use WAL of rocksdb when doing the replication between dragonboat instances and disable "tan"?

mentioning coz there are 2 replication logs used. 1 tan 1 rocksdb's wal
isnt it more efficient to just use one?

p.s. : i was only thinking so with reference to on-disk replication example and implementing it as a client-server on disk now.

**Comment by kevburnsjr** [comment]
> can I disable WAL

You want to disable Dragonboat's WAL?  
If so, I'd recommend just setting the WAL directory to a `tmpfs` mount (in-memory filesystem).  
Whether that use case meets your durability requirements depends on your application but it will improve performance.

**Comment by kolinfluence** [comment]
@kevburnsjr ok thx

**Comment by lni** [comment]
I tried tmpfs a few years ago, for whatever reason, got something like 15% increase in terms of throughput when compared to Intel P4510/P5510. Never got time to look into more details, I *guess* those companies stopped selling RAM disks backed by a battery for a good reason - the performance is no longer that competitive when compared with modern enterprise SSDs.
