### ISSUE TITLE
it's impressive work. been trying to use dragonboat ini and my suggestions and "comments" on dev improvement experience.

### ISSUE THREAD

**Issue by kolinfluence** [lni/dragonboat#309]
it's a great work no doubt. a lot of effort and thought put into it already.
these are further areas of improvement i think can greatly enhance ease of adoption and performance.

1. the development api is truly complicated however you can simplify it with user defined "handler" functions and of course provide a few other options to get their feet wet asap without so many more mental overhead. e.g. please reference
redhub
https://github.com/IceFireDB/redhub/blob/main/example/server.go
redcon
https://github.com/tidwall/redcon/blob/master/example/clone.go

hertz examples provides easy ways for people to get something basic up and running really fast
https://github.com/cloudwego/hertz-examples

definitely some simple doc writeup on the pure basic will help a bit.

2. i think port reuse can definitely speed up more but that is a bit more extreme than necessary, just my thoughts.
because the program's "user" defined functions are not as programmer friendly, it's not easy to help write examples for greater adoption. 

3. change to use xxh3 https://github.com/zeebo/xxh3 instead of xxhash2
however, considering not many people will go for such extremities, it's very good at this stage already. will be using it.
so thx. looking forward to v4 completion.

**Comment by kolinfluence** [comment]
@ini forget about the port reuse thing. it's fine without port reuse feature.

managed to get a lot of things working but i have two more questions 
1. for on disk https://github.com/lni/dragonboat-example/blob/master/ondisk/main.go, if i use addr, if i put them as daisy chained ip:port, does the whole "raft group" knows about everyone else?
2. do i put them as different addr or do i use the "leader" addr for all replicas?
```
addr := flag.String("addr", "", "Nodehost address")
```
pls help answer my questions so i can share my example for people to use as a simple "kv" / simplified etcd replacement.

p.s. : i've implemented Delete and Iterate function to the ondisk feature. now doing the ttl feature.

**Comment by kevburnsjr** [comment]
`addr` is the bind address for the raft API listener.  
`initialMembers` is built from var `addresses`.  
It contains the raft API address for each of the hosts.

I wrote the optimistic write lock example. Recommend comparing for reference.
https://github.com/lni/dragonboat-example/blob/master/optimistic-write-lock/main.go

**Comment by kolinfluence** [comment]
@kevburnsjr 
1. can the initialMembers grow by adding to it dynamically?
2. do i put them as different addr or do i use the "leader" addr for all replicas?

**Comment by kevburnsjr** [comment]
`initialMembers` is used when starting a shard replica.  
Typically you don't grow the number of replicas in a shard. It's usually fixed at 3 or 5.  
If you did want to add a replica to a shard that's already bootstrapped you would have it join the shard.

I recommend reading the documentation for StartReplica.  
https://pkg.go.dev/github.com/lni/dragonboat/v4#NodeHost.StartReplica

Dragonboat does not have a centralized node host registry or a centralized shard registry so you'll need to supply a set of raft addresses (or nodeHostIDs when using  `Gossip` and `AddressByNodeHostID`) as initialMembers every time you start a replica for a new shard.

I am building a [cluster coordinator](https://github.com/logbn/zongzi) to help automate some of these tasks but it's still a work in progress.

Remember that etcd is a database and dragonboat is a consensus library.

- [etcd's raft library](https://github.com/etcd-io/raft) is about 17,000 lines of code across 100 files.
- [etcd itself](https://github.com/etcd-io/etcd) is about 170,000 lines of code across 1,000 files not including the raft library.

If you want to build a production grade database using dragonboat you have a lot of hard work ahead.

**Comment by kolinfluence** [comment]
@kevburnsjr possible to check codislab/codis so can reduce the time to get the cluster coordinator up? maybe we can just use a modified codis to get the job done

https://github.com/CodisLabs/codis/

**Comment by kevburnsjr** [comment]
You may be able to use that, yes.
