### ISSUE TITLE
i cant find the location on how to switch to use tan log

### ISSUE THREAD

**Issue by kolinfluence** [lni/dragonboat#311]
@lni would like to remove anything to do with pebbledb, how do i first use tan log?

found info here without mentioning how to use tan log.

also, how to disable pebbledb for the log if i use tan log too.

that's all. trying out now. trying to get it compile. go mod vendor is not helping with error message here:
https://github.com/lni/dragonboat-example/issues/28

**Comment by kevburnsjr** [comment]
I've never used tan but it seems pretty straight forward after reading the code.  
Probably something like this:
```go
import (
	"github.com/lni/dragonboat/v4"
	"github.com/lni/dragonboat/v4/config"
	"github.com/lni/dragonboat/v4/plugin/tan"
)

func main() {
	exp := config.GetDefaultExpertConfig()
	exp.LogDBFactory = tan.Factory
	nh, err := dragonboat.NewNodeHost(config.NodeHostConfig{
		Expert: exp,
	})
}
```
