### ISSUE TITLE
what does this mean? dragonboat: [00000:00003] had 6 LocalTick msgs in one batch

### ISSUE THREAD

**Issue by kolinfluence** [lni/dragonboat#312]
dragonboat: [00000:00003] had 6 LocalTick msgs in one batch
 
it just shows itself up in message log. how to disable this message?

**Comment by kevburnsjr** [comment]
It's a warning so you _could_ lower the log level.
```go
import (
	"github.com/lni/dragonboat/v4/logger"
)

logger.GetLogger("dragonboat").SetLevel(logger.ERROR)
```

**Comment by kolinfluence** [comment]
@kevburnsjr possible to help answer the rest of the issues i've asked?

been coding heavily internal to expand the examples. i will contribute back improved examples i've done.

**Comment by kevburnsjr** [comment]
I answered several. Feel free to close the issues if you find the answers satisfactory.

**Comment by lni** [comment]
@kolinfluence in general, such warning means your node is overloaded.
