### ISSUE TITLE
Refocusing on core consensus features  

### ISSUE THREAD

**Issue by lni** [lni/dragonboat#32]
Shortly before the dragonboat source code was made publicly available in Jan. 2019, some changes were made to include features not directly related to consensus. For example, the C++ binding was included in the release and the Master server support was refactored from the Drummer package hoping users might be able to use it. 

It has become clear to me now that dragonboat should just focus on the core consensus features. In the next few weeks - 

1. the IMasterClient interface in master.go will be removed. A method named GetNodeHostInfo() will be added to the NodeHost struct, it returns the current NodeHostInfo instance. Users can choose how their Master client/server are going to be built, other than providing the above NodeHostInfo record, Dragonboat will no longer get involved in how distributed NodeHost instances are managed. 

2. The drummer package will be updated accordingly and it will be moved to internal/drummer. It can still be used as a reference implementation of the Master server concept but it will become an internal package. 

3. The future of the C++ binding will be decided once the above item 1 and 2 are done. It might be moved to a separate repo (e.g. github.com/lni/dragonboat-cpp).

**Comment by gensmusic** [comment]
the ` GetNodeHostInfo` is the exact way we want to use. Currently I have to fork the repo and export `GetNodeHostInfo` myself. I will switch back when this is done.

**Comment by gensmusic** [comment]
Another question, can I use the info from `logdb.ListNodeInfo()` when I restart a nodehost? I didn't see there is a delete in logdb, so I can assume it contains the full infomation of all clusters.

**Comment by lni** [comment]
@gensmusic the above item 1 and 2 are already done in our private development branch. 

GetNodeHostInfo() will return the following NodeHostInfo instance and its definitions are provided below. Let me know if you see anything missing or strange. 

```
// ClusterInfo is a record for representing the state of a Raft cluster based
// on the knowledge of the local NodeHost instance.
type ClusterInfo struct {
  // ClusterID is the cluster ID of the Raft cluster node.
  ClusterID uint64
  // NodeID is the node ID of the Raft cluster node.
  NodeID uint64
  // IsLeader indicates whether this is a leader node.
  IsLeader bool
  // Nodes is a map of member node IDs to their Raft addresses.
  Nodes map[uint64]string
  // ConfigChangeIndex is the current config change index of the Raft node.
  // ConfigChangeIndex is Raft Log index of the last applied membership
  // change entry.
  ConfigChangeIndex uint64
  // Pending is a boolean flag indicating whether details of the cluster node
  // is not available. The Pending flag is set to true usually because the node
  // has not had anything applied yet.
  Pending bool
}

// NodeHostInfo provides info about the NodeHost, including its managed Raft
// cluster nodes and available Raft logs saved in its local persistent storage.
type NodeHostInfo struct {
  // RaftAddress is the public address and the identifier of the NodeHost.
  RaftAddress string
  // Region is the region of the NodeHost.
  Region string
  // ClusterInfo is a list of all Raft clusters managed by the NodeHost
  ClusterInfoList []ClusterInfo
  // LogInfo is a list of raftio.NodeInfo values representing all Raft logs
  // stored on the NodeHost.
  LogInfo []raftio.NodeInfo
}
```

As a breaking change to the APIs, it is being developed as a part of the 3.0 release with other major new features, so it will take another couple of weeks to be made available to the Master branch. 

For ListNodeInfo(), yes, it should contain all cluster Node Info. When the new GetNodeHostInfo() API is released, you can get the node info from the LogInfo field of the returned NodeHostInfo instance. For now, the same info is provided to the SendNodeHostInfo method of your MasterClient.

**Comment by gensmusic** [comment]
looks good to me. However is it possible to add `IsObserver` or something similiar so we can known if a raft node is an observer ?

**Comment by lni** [comment]
it will eventually be added to the NodeHostInfo type, for now you can get such observer info from the GetClusterMembership() API.

**Comment by gensmusic** [comment]
ok, cool. Thanks, @lni

**Comment by lni** [comment]
See #46 for progress.
