### ISSUE TITLE
Where can I view the original proto file?

### ISSUE THREAD

**Issue by aierui** [lni/dragonboat#320]
I didn't find any `.proto` format files in the latest commit of the repository.

**Comment by lni** [comment]
Dragonboat's serializable types can not be generated by protobuf directly, it uses protobuf + other serialization framework + hand written optimizations.

**Comment by aierui** [comment]
@lni Thanks guidance, I understand this part of the logic in general.

**Comment by lni** [comment]
just manually change the go files.
