### ISSUE TITLE
Custom INodeRegistry support

### ISSUE THREAD

**Issue by tylerwilliams** [lni/dragonboat#326]
I'm interested in using Dragonboat's gossip feature but I would like to be able to use a different implementation (serf) or send additional information over the gossip network.

There doesn't appear to be a way to get access to the underlying memberlist instance or to provide a custom one.

Would you be open to a pull request [similar to this one](https://github.com/lni/dragonboat/commit/6490d3d67b20e691b41f307833e6c61203a65abc) that would add support for external registry functions?

**Comment by lni** [comment]
I am interested. 

Please allow a few days so I can checkout serf. To be honest, memberlist is a headache, I had many issues with it. If serf can be used as a safer replacement, maybe just get rid of the memberlist module and use serf.

**Comment by lni** [comment]
it seems serf uses memberlist.

**Comment by tylerwilliams** [comment]
> it seems serf uses memberlist.

Yeah it does :( There are [other gossip libraries](https://github.com/clockworksoul/smudge) but I have not used them.

The main reason we want this change is to be able to send our own data via memberlist.

**Comment by tylerwilliams** [comment]
Alright I went ahead and sent https://github.com/lni/dragonboat/pull/327 which adds this against master. LMK what you think. Thanks
