### ISSUE TITLE
TAN Status

### ISSUE THREAD

**Issue by benbjohnson** [lni/dragonboat#328]
I'm evaluating Dragonboat for an application and I was wondering what the status of the `tan` storage engine is? It looks like MatrixOne is using it [here](https://github.com/matrixorigin/matrixone/blob/9ba26f754ace047e9d8ee02285517ebd43070962/pkg/logservice/store.go#L76). 

If I'm starting from scratch, is it generally considered stable enough that I should use it rather than the Pebble implementation? My application has large writes (which are broken up into multiple smaller messages) so the reduced write amplification is appealing.

**Comment by lni** [comment]
Hi @benbjohnson 

Tan was developed in early 2021, a few users have been using it for 12-18 months. My understanding is that no data corruption bug got reported and I am not aware of any pending issue. If that is a strong enough indicator, you may consider tan as stable. Another factor you may want to consider is that lot of the Tan code is derived from pebble, which is pretty stable I'd say. 

For myself, I'd definitely use it in my own production projects. 

Please let me know if you see anything broken/strange. If you have time, maybe read the code and provide some review comments, that will be highly appreciated. Thanks.
