### ISSUE TITLE
how to know the cluster is first create or recovery?

### ISSUE THREAD

**Issue by fishjam** [lni/dragonboat#333]
### Dragonboat version
v3.3.8

### 中文
你好, 我想问一下, 在调用  `NodeHost.StartCluster` 后, 怎么知道该 Cluster 是 第一次启动, 还是停止后重新启动?

**Comment by lni** [comment]
It is your application's responsibility to keep such info, e.g. just create a flag file on the local disk next to the Nodehost folder to record when the shard is first created.
