### ISSUE TITLE
Add disk based state machine support

### ISSUE THREAD

**Issue by lni** [lni/dragonboat#34]
When all state machine data is stored on disk, there is no need to periodically generate snapshots as the state is always available on disk. 

Add such disk based state machine support to dragonboat and allow snapshot to be generated and streamed when it is actually required. 

Note that this is more like an optimization to further save disk space and bandwidth consumption. The current released version of Dragonboat can easily handle State Machines that use disks heavily.

**Comment by iknite** [comment]
This will be very useful to our project https://github.com/bbva/qed since this is our very use case. 

If you need more input it will be gladly provided. 

Great project by the way!

**Comment by lni** [comment]
@iknite disk based state machine has already been added in a private dev branch, it is being actively tested.

**Comment by lni** [comment]
v3.0 beta with on disk state machine support is now available for review & testing. 

https://github.com/lni/dragonboat/tree/beta-release-3.0

Please see the README.md file for a list of other changes.

**Comment by iknite** [comment]
Hi, 

I'm just testing the features and It shows the following error:
https://github.com/iknite/raft-example/blob/dragonboat/error-notes.md

Sometimes it works, and halts `ab` execution, then launching it again will show the problem.

I'm just using gorocksdb master branch and the changes in:
https://github.com/iknite/raft-example/blob/dragonboat/error.patch

Please let me know If I can help somehow.
Thanks again!

**Comment by lni** [comment]
@iknite 

Thanks for reporting the bug! I've opened issue #59 to address your reported bug.

**Comment by lni** [comment]
in master branch, ready to be released.
