### ISSUE TITLE
possible to do a pubsub example with websocket?

### ISSUE THREAD

**Issue by ouvaa** [lni/dragonboat#345]
it'll be amazing if this can work as a pubsub with websocket. needing this feature not sure if can be done.

currently looking at nats.io but i really hope dragonboat can do an example on this.

**Comment by lni** [comment]
hi there, please note that this library is a consensus library, it does one thing and one thing only, that is distributed consensus. All other paradigms, such as pubsub/websocket are not directly relate to this library. 

thanks.
