### ISSUE TITLE
Last index of the replicas

### ISSUE THREAD

**Issue by antmat** [lni/dragonboat#351]
Hi!
Is there a way to know LastIndex of the replicas of the raft cluster? 
We wanted to detect stale nodes in our program, but right now it seems there is no such functionality.

Thanks!

**Comment by kevburnsjr** [comment]
Operations like this are probably best performed out of band.
Just make a request to each node, perform a stale read and compare the results.

**Comment by lni** [comment]
@antmat 

to detect stale node, you can just issue a ReadIndex request on the node and see whether it can be successfully completed. stale nodes will cause the ReadIndex operation to timeout if the "staleness" is more significant than the specified timeout value.
