### ISSUE TITLE
Question about log persistence when follower receive AE

### ISSUE THREAD

**Issue by tt67wq** [lni/dragonboat#360]
When followers receive Replicate message, things work like this:

<img width="624" alt="image" src="https://github.com/lni/dragonboat/assets/12907812/4c88b926-9350-452c-a233-264a4279e1c0">

But raft thesis section 10.2.1 says, "**_The leader may even commit an entry before it has been written to its own disk, if a majority of followers have written it to their disks; this is still safe._** "
<img width="805" alt="image" src="https://github.com/lni/dragonboat/assets/12907812/e0e18de8-e454-4388-b598-e1b46580d2f6">
I have some questions about this. Is it safe for the follower to reply that the copy was successful immediately after receiving the message and writing it to memory?

**Comment by lni** [comment]
@tt67wq for general question on raft, you may want to use the official raft mailing list, see link below. the author of raft is there so you can usually get more accurate & authoritative answers.
 
https://groups.google.com/forum/#!forum/raft-dev  

for your question above, no, it is not safe to allow any follower to skip such persistent storage before acknowledging.
