### ISSUE TITLE
Please make this feature possible with ondisk example version, uhaha kvdb

### ISSUE THREAD

**Issue by sprappcom** [lni/dragonboat#362]
with reference to :
https://github.com/lni/dragonboat/issues/256

this is amazing:
https://github.com/tidwall/uhaha/tree/master/examples/kvdb
this should be how it should be shown as example for the ondisk example of dragonboat.

between stability vs performance in raft implementation, i choose stability, reliability first BUT...

can you check out kvdb? this is how it should work. if i delete the node and recover it. it just works in a new directory.

please make it work this way for the ondisk example! i can add back the node with node number etc and i can sleep better knowing the raft just works as meant to be!

pls help make this possible. will donate coffees.

**Comment by sprappcom** [comment]
@lni @kevburnsjr

**Comment by lni** [comment]
Your issue has been fully addressed in https://github.com/lni/dragonboat/issues/362
