### ISSUE TITLE
How to delete all replicas of a specific shard? 

### ISSUE THREAD

**Issue by luluz66** [lni/dragonboat#364]
In dragonboat, I can use `nodehost.SyncRequestDeleteReplica` to delete a replica of a specific shard. But it doesn't let me to delete the last replica of the shard. ([code](https://github.com/lni/dragonboat/blob/6a1623140f27d3da7ebdbeeb9d2cf16eed5a5c43/internal/rsm/membership.go#L341))

How can I delete a shard completely, in particular, remove all replicas of this shard?

**Comment by lni** [comment]
I don't think you can remove all replicas of a shard, as a shard with 0 replica is not considered as valid in dragonboat. 

To remove a shard completely, including all associated data of the shard, you can just stop all replicas and use the RemoveData() method on all involved machines to delete all associated data. Note that you are not suppose to restart those replicas once their data is removed.
