### ISSUE TITLE
How Do I Obtain the IP Addresses of All Nodes?

### ISSUE THREAD

**Issue by xiatianqiuyu** [lni/dragonboat#365]
How Do I Obtain the IP Addresses of All Nodes?

**Comment by lni** [comment]
you get to choose what machines you want to use for running all your NodeHost instances, their IP addresses should be available to you no matter whether you use dragonboat or not. 

there is no specific API to return all IP addresses involved. please note that dragonboat is a consensus library, it does one thing and one thing only, that is consensus. thanks.
