### ISSUE TITLE
A few recommended storage engine libraries - 推荐几个存储库

### ISSUE THREAD

**Issue by huanyang712** [lni/dragonboat#38]
https://github.com/tidwall/buntdb

https://github.com/xujiajun/nutsdb

**Comment by lni** [comment]
Thanks for the info.

**Comment by lni** [comment]
For those who might be interested - 

To use your favourite storage engine in Dragonboat, just implement the ILogDB interface defined in the raftio package and pass a factory function that creates such instance to the LogDBFactory field of your NodeHostConfig.
