### ISSUE TITLE
switch to goleveldb for pure go solution

### ISSUE THREAD

**Issue by chrislusf** [lni/dragonboat#4]

**Comment by lni** [comment]
I am investigating a list of alternative options, goleveldb will be one of them to be carefully evaluated.

**Comment by h7kanna** [comment]
https://github.com/dgraph-io/badger is a pure go alternative to RocksDB.

**Comment by vtolstov** [comment]
Please provide interface for storagw,so leveldb or badger can be used transparently

**Comment by ghost** [comment]
Great to see a non cgo option.

There are a few nice badger wrappers.


https://github.com/zippoxer/bow

https://github.com/alash3al/srchx

**Comment by lni** [comment]
did some research on this and I realized that badger is used by ipfs-go. badger's team also has this cash for data loss bug challenge ongoing and no one has managed to make some money out of it by identifying data corruption/loss bugs. I'd consider that as a big boost of confidence.  :)

anyone has info on how reliable is goleveldb? @chrislusf any experience on that?

**Comment by h7kanna** [comment]
Its not only that, badger is used by their product dgraph which itself uses badger for raft wal storage.
https://github.com/dgraph-io/dgraph/blob/master/raftwal/storage.go#L67

**Comment by xianglinghui** [comment]
I think provide interface for storage is more better，just like etcd/raft，which provides only the core of raft.

**Comment by lni** [comment]
@xianglinghui, such interface is already provided, please have look at the package github.com/lni/dragonboat/raftio for their definitions. you can build your own storage/networking implementations and use them by providing a factory method to your NodeHostConfig.

**Comment by xianglinghui** [comment]
@lni It's great.

**Comment by funlake** [comment]
Stuck in rocksdb installing when  `make install-rocksdb-ull`,anyone help?
```
gzip: stdin: unexpected end of file
rocksdb-5.13.4/monitoring/instrumented_mutex.cc
rocksdb-5.13.4/monitoring/instrumented_mutex.h
rocksdb-5.13.4/monitoring/iostats_context.cc
rocksdb-5.13.4/monitoring/iostats_context_imp.h
rocksdb-5.13.4/monitoring/iostats_context_test.cc
rocksdb-5.13.4/monitoring/perf_context.cc
rocksdb-5.13.4/monitoring/perf_context_imp.h
rocksdb-5.13.4/monitoring/perf_level.cc
rocksdb-5.13.4/monitoring/perf_level_imp.h
rocksdb-5.13.4/monitoring/perf_step_timer.h
rocksdb-5.13.4/monitoring/statistics.cc
rocksdb-5.13.4/monitoring/statistics.h
rocksdb-5.13.4/monitoring/statistics_test.cc
rocksdb-5.13.4/monitoring/thread_status_impl.cc
rocksdb-5.13.4/monitoring/thread_status_updater.cc
tar: Unexpected EOF in archive
tar: Unexpected EOF in archive
tar: Error is not recoverable: exiting now
make: *** [get-rocksdb] Error 2
```

**Comment by lni** [comment]
@funlake your issue has been moved to #16 and I've replied to it. Please use the #16 to follow up.

**Comment by Fullstop000** [comment]
Although goleveldb's performance is really attractive, it should be considered carefully since it doesn't provide a proof of crash consistency .

**Comment by lni** [comment]
@Fullstop000 thanks for the input, I am not currently looking into goleveldb. 

Any info on the crash consistency of some pure go kv-store libraries?

**Comment by Fullstop000** [comment]
Badger did their work https://blog.dgraph.io/post/alice/
I'm not familiar with the source code and performance of Badger so just for reference

**Comment by lni** [comment]
@Fullstop000 thanks for the info.

**Comment by lni** [comment]
I've add some **experimental** code to make badger to work with Dragonboat. The code is available in 

https://github.com/lni/dragonboat/tree/badger-logdb-experimental

As mentioned above, this is some **experimental** code use to see how badger works. It should never be used in production. 

I'd like to point out that there are outstanding issues preventing badger support to be added - 

- it leaks goroutines
- sstables are not checksumed (vlog is checksumed)

Feel free to see badger's issue page for more details.

**Comment by lni** [comment]
BoltDB is another library I closely checked, etcd has a fork of it, the repo seem to be pretty actively maintained. However, there are open data corruption issue pending investigation/fix.

**Comment by lni** [comment]
Closing this one as I don't think goleveldb will be supported any time soon. 

Badger support related discussions has been moved to https://github.com/lni/dragonboat/issues/18

If there is any other alternative kv-store library that you want to recommend, please feel free to open a new issue.
