### ISSUE TITLE
binding.h not found in vendor

### ISSUE THREAD

**Issue by isnlan** [lni/dragonboat#41]
# github.com/snlansky/silk/vendor/github.com/lni/dragonboat/internal/cpp
In file included from ../vendor/github.com/lni/dragonboat/internal/cpp/wrapper.go:34:0:
./wrapper.h:19:10: fatal error: dragonboat/binding.h: No such file or directory
 #include "dragonboat/binding.h"
          ^~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
When I use dep or go mod, the header file will not be found.This makes it impossible to compile the go binary using the docker image.

**Comment by lni** [comment]
It has nothing to do with whether you build it in docker.  If you look at dragonboat's release-2.1 branch tree or the released .zip/.tar.gz source files, there is a top level package named binding - 

https://github.com/lni/dragonboat/tree/release-2.1

however for whatever reason it is not in your vendor folder - 

https://github.com/snlansky/silk/tree/addmod/vendor/github.com/lni/dragonboat

**Comment by lni** [comment]
@snlansky can you provide a bit more info on how you maintain your vendor folder? did you manually remove the github.com/lni/dragonboat/binding package?

**Comment by isnlan** [comment]
When I used dep to generate the vendor folder, it was visible from the vendor, but the header file was missing at compile time, so I eventually removed it from the vendor

**Comment by lni** [comment]
@snlansky 

I've made the v2.1.4 release for some RocksDB related issues, as part of that v2.1.4 release, I've also changed the dragonboat package to no longer rely on the internal/cpp package. Please try v2.1.4 and let me know if you still have the same problem. 

I also created a dummy project with go mod to reproduce the issue you had, the binding package is not included in my vendor folder when I run `go mod vendor`. It seems to be a go mod issue and I will dig deeper.

**Comment by isnlan** [comment]
@lni  
Thank you very much for your attention to my question

**Comment by lni** [comment]
@snlansky please close this issue if it has been resolved. thanks.
