### ISSUE TITLE
How to get the state of each node

### ISSUE THREAD

**Issue by huanyang712** [lni/dragonboat#43]
When a node fails, how to get the it’s state ?

**Comment by lni** [comment]
In the current v2.1.x releases, you can implement your own IMasterClient type to get periodically notified of the states of all Raft nodes managed by the NodeHost instance. 

In the coming v3.0 release, which is expected to be released as Beta in 2-3 weeks, there will be a new API called GetNodeHostInfo. It returns the states of all Raft nodes managed by the NodeHost instance. 

Note that how to find out node failures itself has nothing to do with consensus/Raft. It is a general topic essential to all distributed systems.
