### ISSUE TITLE
build docker images failed

### ISSUE THREAD

**Issue by isnlan** [lni/dragonboat#44]
Dockerfile
`
FROM golang:1.11
MAINTAINER silk
ENV GOCACHE=off
ENV GOPATH=/opt/gopath
ENV CGO_CFLAGS="-I/path/to/rocksdb/include"
ENV CGO_LDFLAGS="-L/path/to/rocksdb/lib -lrocksdb"

RUN mkdir -p "$GOPATH/src" "$GOPATH/bin" && chmod -R 777 "$GOPATH"
WORKDIR $GOPATH

RUN apt-get update && apt-get install -y build-essential libncurses-dev libtool make gcc g++ unzip

RUN go get -u -d github.com/lni/dragonboat; \
    cd $GOPATH/src/github.com/lni/dragonboat; \
    make install-rocksdb-ull
`
ln -fs librocksdb.so.5.13.4 librocksdb.so
ln -fs librocksdb.so.5.13.4 librocksdb.so.5
ln -fs librocksdb.so.5.13.4 librocksdb.so.5.13
make[1]: Leaving directory '/opt/gopath/src/github.com/lni/dragonboat/build/rocksdbtmp/rocksdb-5.13.4'
Makefile:265: recipe for target 'install-rocksdb-lib-ull' failed
/bin/sh: 3: sudo: not found
make: *** [install-rocksdb-lib-ull] Error 127

**Comment by lni** [comment]
@snlansky 

It failed because there is no sudo support.  

Please have a quick look on the Dockerfiles for building docker images used in our nightly tests - 
https://github.com/lni/dragonboat/blob/master/scripts/Dockerfile-debian-9.4
