### ISSUE TITLE
duplicate commit data

### ISSUE THREAD

**Issue by isnlan** [lni/dragonboat#45]
IStateMachine.Update always receives duplicate data when the node is restarted.

**Comment by lni** [comment]
@snlansky 

No, nothing is duplicated. 

After a node is restarted, it must either restore its data from a snapshot image or re-apply all committed data from the Raft log so the state machine can maintain consistent state. This is the exact default behaviour described by the Raft thesis. It is documented in statemachine/rsm.go - 

> // When created, an IStateMachine instance should always start from an empty
> // state. Dragonboat will use saved snapshots and Raft Logs to help a restarted
> // IStateMachine instance to catch up to its previous state.

In short, when your IStateMachine is restarted, the state machine must be empty, then it should follow whatever received by its Update() or RecoverFromSnapshot() methods to get it fully restored.  

Your application probably don't want such committed log entry to be received by the Update method again, e.g. all your StateMachine data might already on disk, such as the one described in the section 5.2 of the Raft thesis. Dragonboat v3.0 to be released in a couple of weeks will provides an IOnDiskStateMachine to support that - but please note that this is just an optimization to make certain types of State Machine more IO efficient.

**Comment by lni** [comment]
@snlansky v3.0 beta is now available for review & testing. It comes with the support for a new state machine type called IOnDiskStateMachine, it can help to address the concern you raised in this issue.
