### ISSUE TITLE
Will the update method be blocked during the process of creating a snapshot?

### ISSUE THREAD

**Issue by rothtty** [lni/dragonboat#48]
If I have a lot of data, I need to take a snapshot, It might take two seconds.
during these two seconds, the state machine cannot update?

**Comment by lni** [comment]
@dydysy When your state machine implements the IConcurrentStateMachine interface, Update() can be concurrently invoked when snapshot is being created.  Your reads to the state machine can also be invoked concurrent to update().

**Comment by rothtty** [comment]
thanks very much.
because I used the release version(2.1.5), so I didn't see the IConcurrentStateMachine interface. hope to release the IConcurrentStateMachine interface as soon as possible.

**Comment by lni** [comment]
@dydysy 

In the coming v3.0 release, an overview wiki will be added to introduce such technical details. also looking forward to have more feedbacks from you. Thanks.

**Comment by lni** [comment]
@dydysy v3.0 beta is now available for review & testing.
