### ISSUE TITLE
Add API to clean up data that belongs to already deleted node 

### ISSUE THREAD

**Issue by lni** [lni/dragonboat#50]
Once a node is removed (NodeHost.RequestDeleteNode) from the Raft cluster, all its data can be removed from the system to free up storage space.  Add API to do that. 

This is requested by a potential user.

**Comment by lni** [comment]
This has been implemented as a new NodeHost API named RemoveData(). It is available for preview & testing in the v3.0 beta release. 

https://github.com/lni/dragonboat/tree/beta-release-3.0

There are some tests in nodehost_test.go that can be used as examples on how to use this new API.

**Comment by lni** [comment]
in master branch, ready to be released soon.

**Comment by xiatianqiuyu** [comment]
Can the function be modified so that deleted nodes can be added to the cluster again after RemoveData is called?
