### ISSUE TITLE
After update hooks feature request

### ISSUE THREAD

**Issue by riaan53** [lni/dragonboat#51]
Hi, 

I have a few subscribers that needs to do `syncReads` once new data for that specific topic or item has changed or is added. Is there a way to accomplish this currently? Currently it looks like the only way is to poll or long poll through the read interface. It would be nice if I can register some hooks or have an update channel.

Thanks!

**Comment by motecshine** [comment]
iStateMachine has a `Update` Interface。 maybe you can implement it to complete your requirements.

**Comment by lni** [comment]
@riaan53 

According to my understanding, you want to be notified once something in your state machine is changed/added. If that is what you want, you can always have some extra code in the Update() method of your IStateMachine to trigger that notification as Update() is the place where things get changed/added in your state machine. The Update() method which is expected to be implemented by your application is your hook - you can do whatever you want both before or after the actual update. 

To make such updates, your application must make proposals (e.g. via SyncPropose) and the successful completion of such proposals means the changes have been applied into your state machine. Your client code that makes such proposals can also trigger such notification as well.

**Comment by riaan53** [comment]
Hi, thanks for the replies!

I managed to get my pattern working by just using additional code in the `Update` method like you suggested (already implemented all interfaces as per docs). I just needed to wrap the `IConcurrentStateMachine` in a parent container to be able to hook into it.
