### ISSUE TITLE
Unknown function signature in drummer client 

### ISSUE THREAD

**Issue by abbccdda** [lni/dragonboat#52]
When trying to build `drummer/server/drummercmd` using `go build main.go`, following exception was triggered:
`drummer/client/nodehost.go:387:14: dc.nh.StartClusterUsingPlugin undefined (type *dragonboat.NodeHost has no field or method StartClusterUsingPlugin)`

The root cause was due to this inclusion refactoring [diff](https://github.com/lni/dragonboat/commit/225ed952ce5cb893903f5f334c38a5e30b988d4c). It moved function `StartClusterUsingPlugin` into outside class `binding.go`, so `drummer/client/nodehost.go` couldn't access it.

**Comment by lni** [comment]
@abbccdda 

drummer/server has been removed in the coming release and the drummer package itself has been moved to internal/drummer.
