### ISSUE TITLE
Integration test for dragonboat

### ISSUE THREAD

**Issue by abbccdda** [lni/dragonboat#53]
Inspired by #52 , wondering whether it makes sense to trigger jenkins test coverage for major codepaths in dragonboat.

**Comment by lni** [comment]
This project uses travis for CI (https://travis-ci.com/lni/). It currently builds the master branch by default for all library packages and their tests. It should probably use travis to build the latest release branch as well.

**Comment by lni** [comment]
It actual builds the latest release branch as well, see the link below - 

https://travis-ci.com/lni/dragonboat/branches

The error discussed in #52 never get caught as those drummer server components were never included in the rebuild-all target.
