### ISSUE TITLE
new features  are separate from the real problem list, which is better.

### ISSUE THREAD

**Issue by motecshine** [lni/dragonboat#54]
New Feature
- [x] Item 1 
- [ ] Item 2 
- [ ] Item 3
- [ ] Item 4

new features  are separate from the real problem list, which is better.

**Comment by motecshine** [comment]
![image](https://user-images.githubusercontent.com/7615270/56561726-5c75a300-65da-11e9-8db4-f46726283c1b.png)

**Comment by lni** [comment]
thanks for the recommendation.
