### ISSUE TITLE
Pluggable Log DB Implementations

### ISSUE THREAD

**Issue by 256dpi** [lni/dragonboat#61]
Thanks for the amazing library. I'm currently trying it out on a project I'm working on and it was a big success until now. :-)

Recently, I wanted to play around with some alternative implementations for the underlying LogDB that are pure Go. To fully implement a custom LogDB and turn off the other implementations to prevent CGO compilation one needs to implement the `raftio.ILogDB` interface and build with the `dragonboat_custom_logdb` build tag. On top of that, a lot of plumbing needs to be reimplemented that has already been solved on the internal `logdb` package. And from a quick glance, the `logdb.IKvStore` looks a lot simpler to implement than `raftio.ILogDB` anyway.

Would it be possible to separate the different LogDB implementations and expose the `logdb.IKvStore` interface?

From an API perspective I could envision the following API:

```go
// RocksDB
config.NodeHostConfig{
	// ....
	LogDBFactory: rocksdb.Factory(),
}

// Pebble
config.NodeHostConfig{
	// ....
	LogDBFactory: pebble.Factory(),
}

// Custom (Simple)
config.NodeHostConfig{
	// ....
	LogDBFactory: kvstore.Wrap(customFactory()),
}
```

The `kvstore.Wrap` would create a `raftio.ILogDB` from a factory that returns `logdb.IKvStore` types.

This approach would even allow to provide CLI flags to select the underlying store.

**Comment by lni** [comment]
The current version has the following behaviour - 

- RocksDB is used by default when NodeHostConfig.LogDBFactory is nil
- When one of those Log DB related built tags is set (e.g. dragonboat_pebble), RocksDB will not be linked so users can use the dragonboat library without installing RocksDB first.  

For the proposed API above, I am wondering how the same behaviour can be maintained? 

For making your own raftio.ILogDB implementations, please note that most of the plumbing code in internal/logdb is not strictly required, e.g. sharded_rdb.go can be entirely ignored when you don't shard the data, background manual compaction is not required if you choose B+ tree based KV stores, you don't need to batch Raft entries or cache previously saved raft states.    

For logdb.IKvStore, it is a private interface and there is no plan to make it public. If you look at previously raised issues, quite a few pure Go alternative KV stores (badger/BoltDB/goleveldb etc) have been investigated.  It takes minimum amount time to add support for an existing KV store, but sadly most KV stores are not reliable enough to store Raft Logs. Quite a few of them can silently corrupt the Raft Log in some corner cases and such bugs are very difficult to debug. A good example here is that even RocksDB must be used with great care -  the range delete feature in RocksDB was recently disabled as it is not stable enough. My concern is that making logdb.IKvStore public won't make dragonboat more reliable (which will always be the No.1 goal) or feature rich.  

Another reason against a general KV style Log DB interface is that I don't believe Key-Value store is the optimal choice for storing Raft Logs. There are actually concrete ongoing discussions/work to move away from KV stores.

**Comment by 256dpi** [comment]
Thanks for the clarifications!

Defaulting to RocksDB if the factory function is nil would not be possible with the proposed API. The user has to import the package actively and set the factory method. Otherwise, the rocksdb package gets linked no matter what the factory function is set to (to accommodate an absent value).

From my experience with Go I never had to build with build tags to select different implementations as this was always done by allow different packages to be imported and combined. While the current approach allows a custom implementation, it does not allow switching between RocksDB and Pebble using a CLI flag since the binary needs to be recompiled. IMHO, this behaviour would be Ok for a final app but since dragonboat is a library it feels weird to me.

The is very easy for existing users to implement, but would break the API stability and thus should be added as part of the upcoming v3 release, if considered.

**Comment by lni** [comment]
> IMHO, this behaviour would be Ok for a final app but since dragonboat is a library it feels weird to me.

I agree that build tags are weird. That being said, please note that -

- Most users are expected to use the default RocksDB based Log DB for now, no dragonboat build tag is involved. 
- When using a custom Log DB implementation, the dragonboat_custom_logdb build tag is optional. As long as the RocksDB library is installed, no build tag will be required. 
- If everything goes well, pebble will eventually become the default Log DB implementation to replace RocksDB. After such transition, all tags can be removed.  

Please also note that, to the maximum of my knowledge, there is currently no suitable pure-go open source Key-Value store that can be used safely for Raft Log DB.

**Comment by lni** [comment]
In the coming v3.0 release - 

1. Rocksdb, leveldb and pebble specific code will be moved into github.com/lni/dragonboat/internal/logdb/driver
2. RocksDB will remain as the default Log DB type when NodeHostConfig.LogDBFactory is nil 
3. Factory functions will be provided so NodeHostConfig.LogDBFactory can be set to such factory functions to use leveldb or pebble based LogDB.
4. Build tags dragonboat_leveldb and dragonboat_pebble tag will be retired. dragonbat_custom_logdb will be kept, it is an optional build tag to avoid requiring with the RocksDB library during compilation. Users don't have to set the dragonbat_custom_logdb build tag when they have the rocksdb library installed. 

The transition plan to use pebble as the default Log DB when it is officially released remains unchanged.

**Comment by lni** [comment]
Deleted my previous post as the information in it is now out of date and can be confusing to users. 

In the current v3.0 beta branch -

You can now set the NodeHostConfig.LogDBFactory field to the provided LevelDB/Pebble based Log DB factory methods from the plugin package. The old build tags named dragonboat_leveldb and dragonboat_pebble have been retired. This still requires you to have the RocksDB library installed (see explanation above). 

To avoid depending on the RocksDB library when using LevelDB/Pebble/your own custom LogDB, there is now a new build tag dragonboat_no_rocksdb. It does only one thing - avoid dependency on RocksDB when building your application.

**Comment by lni** [comment]
@256dpi 

Based on your feedback, the above changes have been made. You can now switch Log DB implementations on CLI if you like. The usage of build tags have been minimized, dragonboat_no_rocksdb will have to stay until pebble is ready to take over the role of RocksDB. 

There is no plan to expose the IKvStore interface to the public, due to the reasons explained in my previous reply. If you want to try other KV implementations, you can always implement your own ILogDB or fork and extend dragonboat to use the IKvStore interface and those existing plumbing code in internal/logdb.

**Comment by 256dpi** [comment]
Thanks for working on this! This makes stuff already a lot easier.
