### ISSUE TITLE
Why On Disk SM need to fsync after each batched update

### ISSUE THREAD

**Issue by lni** [lni/dragonboat#62]
@riaan53 asked the following good question in the chatroom. 

for the disk sm, is the design to fsync after each batch? Seeing as it was already fsynced in raft wal it feels a bit unnecessary to incur the penalty twice. My thinking is that on a crash or restart, recover all items from disk with valid crc and then report that to the open method (like it is now) - the missing items will be replayed as necessary.

**Comment by lni** [comment]
@riaan53

> My thinking is that on a crash or restart, recover all items from disk with valid crc and then report that to the open method (like it is now) - the missing items will be replayed as necessary.

The biggest motivation for using On Disk SM is to make sure that there is roughly one copy of the user data on disk (in SM or in Raft Log DB). Once the committed Raft Log entries are applied into the on disk SM, those Raft Log entries are ready to be removed to release disk space. 

Your mentioned method above won't work because we can't remove anything from the Raft Log if arbitrary amount of applied data might disappear from the On Disk SM after such reboot.

**Comment by lni** [comment]
It probably make sense to add a new method say Fsync() to the IOnDiskStateMachine type, it syncs all in core data to disk. The new Fsync() method is called before compacting the Raft Log. We can then make it optional to fsync for each Update().

**Comment by riaan53** [comment]
Hi @lni , Awesome- thank you for the explanation. That sound like a nice way to achieve that. Let me know what you decide on.

**Comment by lni** [comment]
@riaan53 The above mentioned changes have been implemented, a Sync() method has been added to the IOnDiskStateMachine interface, it is available in the 3.0 beta branch. 

https://github.com/lni/dragonboat/tree/beta-release-3.0

**Comment by riaan53** [comment]
Awesome! Thank you! :)

**Comment by mostcute** [comment]
can you provide an example about how to use IOnDiskStateMachine ::Sync（）?

**Comment by mostcute** [comment]
set sync = false in Update() and impl  IOnDiskStateMachine ::Sync（） like this ?

```

// Sync synchronizes all in-core state of the state machine. Since the Update
// method in this example already does that every time when it is invoked, the
// Sync method here is a NoOP.
func (d *DiskKV) Sync() error {
	db := (*pebbledb)(atomic.LoadPointer(&d.db))
	db.db.Flush()
	return nil
}
```

**Comment by kevburnsjr** [comment]
The flush call looks correct to me.
You can then safely pass `&pebble.WriteOptions{Sync: false}` in all write operations to improve performance.

**Comment by lni** [comment]
@mostcute this is relate to how Pebble can be fsynced, please double check pebble's docs for details. 

As explained in dragonboat's docs, the Sync() method should ensure that everything already updated into the state machine is permanently stored into the physical disk rather than sitting somewhere in some software cache/buffer. How it should be done really depends on how your state machine is going to store data.
