### ISSUE TITLE
Can not add a removed node into the cluster

### ISSUE THREAD

**Issue by hejiew** [lni/dragonboat#72]
how to add a removed node into the cluster?

**Comment by lni** [comment]
It is a feature - removed node is not allowed to be added back. See the implementation in the link below. 

https://github.com/lni/dragonboat/blob/79bcef060698c5c0e200c7f72fc3fda03b99feae/internal/rsm/membership.go#L134

**Comment by xiatianqiuyu** [comment]
Can the function be modified so that deleted nodes can be added to the cluster again after RemoveData is called?
