### ISSUE TITLE
invalid membership change operation will be recorded into raft log

### ISSUE THREAD

**Issue by xianglinghui** [lni/dragonboat#75]
Hi，lni

It seems invalid membership change operation will be recorded into raft log, and will be replayed when restart the node.

I do a RequestDeleteNode call on a cluster which only have one node(itself), then the program panic:

2019-06-23 16:24:51.754526 I | rsm: [01001:00001] applied ConfChange Remove ccid 0, node n00001, index 5
2019-06-23 16:24:51.754585 I | dragonboat: [01001:00001] applied ConfChange Remove for itself
2019-06-23 16:24:51.754606 I | dragonboat: [01001:00001] called requestRemoval()
2019-06-23 16:24:51.754713 C | dragonboat: empty nodes [01001:00001]
2019-06-23 16:24:51.754733 E | utils: worker is panicing, empty nodes [01001:00001]
panic: empty nodes [01001:00001] [recovered]
	panic: empty nodes [01001:00001]

goroutine 62 [running]:
hykv/vendor/github.com/lni/dragonboat/internal/utils/syncutil.(*Stopper).runWorker.func1.1()
	/home/work/hykv_prj/src/hykv/.gopath/src/hykv/vendor/github.com/lni/dragonboat/internal/utils/syncutil/stopper.go:104 +0xf3
panic(0x9e0500, 0xc05fa96150)
	/home/work/go/golang/go1.11.1_goid_build/go/src/runtime/panic.go:513 +0x1b9
hykv/vendor/github.com/lni/dragonboat/internal/utils/logutil/capnslog.(*PackageLogger).Panicf(0xc0001bb0a0, 0xad7d30, 0xe, 0xc05fa96100, 0x1, 0x1)
	/home/work/hykv_prj/src/hykv/.gopath/src/hykv/vendor/github.com/lni/dragonboat/internal/utils/logutil/capnslog/pkg_logger.go:83 +0x161
hykv/vendor/github.com/lni/dragonboat/logger.(*capnsLog).Panicf(0xc00553e060, 0xad7d30, 0xe, 0xc05fa96100, 0x1, 0x1)
	/home/work/hykv_prj/src/hykv/.gopath/src/hykv/vendor/github.com/lni/dragonboat/logger/capnslogger.go:73 +0x60
hykv/vendor/github.com/lni/dragonboat/logger.(*dragonboatLogger).Panicf(0xc00001fb00, 0xad7d30, 0xe, 0xc05fa96100, 0x1, 0x1)
	/home/work/hykv_prj/src/hykv/.gopath/src/hykv/vendor/github.com/lni/dragonboat/logger/logger.go:120 +0x74
hykv/vendor/github.com/lni/dragonboat.(*node).captureClusterState(0xc0741ea000)
	/home/work/hykv_prj/src/hykv/.gopath/src/hykv/vendor/github.com/lni/dragonboat/node.go:1331 +0x373
hykv/vendor/github.com/lni/dragonboat.(*node).ConfigChangeProcessed(0xc0741ea000, 0xe8a1b8f82a6334a6, 0x1)
	/home/work/hykv_prj/src/hykv/.gopath/src/hykv/vendor/github.com/lni/dragonboat/node.go:260 +0x5c

Then I restart my program, and call StartOnDiskCluster on NodeHost to restart the cluster，but it panic again:

2019-06-23 16:33:03.435160 I | rsm: [01001:00001] applied ConfChange Remove ccid 0, node n00001, index 5
2019-06-23 16:33:03.435168 I | dragonboat: [01001:00001] applied ConfChange Remove for itself
2019-06-23 16:33:03.435178 I | dragonboat: [01001:00001] called requestRemoval()
2019-06-23 16:33:03.435185 C | dragonboat: empty nodes [01001:00001]
2019-06-23 16:33:03.435197 E | utils: worker is panicing, empty nodes [01001:00001]
panic: empty nodes [01001:00001] [recovered]
	panic: empty nodes [01001:00001]

goroutine 88 [running]:
hykv/vendor/github.com/lni/dragonboat/internal/utils/syncutil.(*Stopper).runWorker.func1.1()
	/home/work/hykv_prj/src/hykv/.gopath/src/hykv/vendor/github.com/lni/dragonboat/internal/utils/syncutil/stopper.go:104 +0xf3
panic(0x9e0500, 0xc05b2ac450)
	/home/work/go/golang/go1.11.1_goid_build/go/src/runtime/panic.go:513 +0x1b9
hykv/vendor/github.com/lni/dragonboat/internal/utils/logutil/capnslog.(*PackageLogger).Panicf(0xc005553060, 0xad7d30, 0xe, 0xc05b2ac400, 0x1, 0x1)
	/home/work/hykv_prj/src/hykv/.gopath/src/hykv/vendor/github.com/lni/dragonboat/internal/utils/logutil/capnslog/pkg_logger.go:83 +0x161
hykv/vendor/github.com/lni/dragonboat/logger.(*capnsLog).Panicf(0xc005562020, 0xad7d30, 0xe, 0xc05b2ac400, 0x1, 0x1)
	/home/work/hykv_prj/src/hykv/.gopath/src/hykv/vendor/github.com/lni/dragonboat/logger/capnslogger.go:73 +0x60
hykv/vendor/github.com/lni/dragonboat/logger.(*dragonboatLogger).Panicf(0xc00001fb00, 0xad7d30, 0xe, 0xc05b2ac400, 0x1, 0x1)
	/home/work/hykv_prj/src/hykv/.gopath/src/hykv/vendor/github.com/lni/dragonboat/logger/logger.go:120 +0x74
hykv/vendor/github.com/lni/dragonboat.(*node).captureClusterState(0xc00555b200)
	/home/work/hykv_prj/src/hykv/.gopath/src/hykv/vendor/github.com/lni/dragonboat/node.go:1331 +0x373
hykv/vendor/github.com/lni/dragonboat.(*node).ConfigChangeProcessed(0xc00555b200, 0xe8a1b8f82a6334a6, 0x1)
	/home/work/hykv_prj/src/hykv/.gopath/src/hykv/vendor/github.com/lni/dragonboat/node.go:260 +0x5c
hykv/vendor/github.com/lni/dragonboat/internal/rsm.(*StateMachine).handleEntry(0xc05b158000, 0x4, 0x5, 0x1, 0xe8a1b8f82a6334a6, 0x0, 0x0, 0x0, 0xc000024610, 0xa, ...)

It seems the NodeHost replay the invalid membership change operation, then lead to panic.

**Comment by lni** [comment]
When you only have 1 node in the cluster and you choose to delete it, Dragonboat followed your instruction and did exact what you requested. Once the Config Change proposal is committed, it is permanently stored in the Raft Log and it will always be replayed. I don't see anything invalid here. 

The root question here is that why you choose to delete the only node from the cluster? If you intentionally did that, well your request has been correctly committed and applied.

**Comment by lni** [comment]
@xianglinghui 

I am waiting for further information from you on why the only node in a Raft cluster is deleted. I'd like to  understand is there any real use case for such membership change.

**Comment by lni** [comment]
I have updated the membership change part, it has been made more resilient to the following unexpected requests - 

* deleting the only node from a cluster will be rejected
* promoting an observer using a AddNode request with different address will be rejected

The following bug has been fixed - 
* adding an existing node/observer with different address will be rejected

v3.0 release has been patched, v3.0.2 has been released
