### ISSUE TITLE
example/KVStore is mentioned in doc, but it is missing in source code 

### ISSUE THREAD

**Issue by thesues** [lni/dragonboat#9]

**Comment by lni** [comment]
The KVStore example was originally built for demonstrating how to use the optional component called drummer. The drummer component is currently used by some tests and serves as a reference implementation of the Master server concept (see master.go). Note that the master server concept itself is optional as well, many people won't need/use it. 

As both of them are optional, plus there is already quite a lot of stuff included in the first release, I decided to remove all examples on drummer. Sadly some references to those examples were left in the docs by mistake.  

Thanks for reporting the issue, I will fix it in docs soon.

**Comment by lni** [comment]
fixed.
