### ISSUE TITLE
碰到读写性能严重下降 - Read/Write performance degradation using the C++ wrapper

### ISSUE THREAD

**Issue by 50829637** [lni/dragonboat#91]
你好，发现dragonboat是个非常优秀，非常容易上后，在性能压测过程碰到性能困惑，想咨询下是否使用方法不得当：
1、机器环境：amd 8核 16G，三台， 三台服务器ping 延迟：0.5ms。
2、纯内存，就一个变量。
3、请求直接命中Leader提交

发现现象：
1、仅put，单cluster，min:5ms，max:35ms，avg:18ms，从服务端统计看，2.3w/秒，并发连接：600
2、仅get，单cluster，min:3ms，max:22ms，agv:13ms，从服务端统计看，3.8W/秒，并发连接: 600
3、读写=10:1，单cluster，min:3ms，max:1.5秒，从服务端统计看，读:1.3W/秒，写1000次/秒，并发连接 600

读写混合的时侯，性能下降特别厉害，不知道为何？

**Comment by lni** [comment]
The biggest concern here is that your average latency is 13ms when doing read only queries. I'd recommend to profile your own code to see what is introducing such huge delays. 

Using 600 concurrent clients on 1 Raft cluster backed by a in memory state machine, when ping time between two nodes are 0.6ms, I got close to 300,000 reads per second and the avg delay is 2ms -  

```
2019/07/28 12:22:08  - Completed/Total: 1000000/12000000, 257931/IOPS
2019/07/28 12:22:12  - Completed/Total: 2000000/12000000, 301841/IOPS
2019/07/28 12:22:15  - Completed/Total: 3000000/12000000, 305530/IOPS
2019/07/28 12:22:18  - Completed/Total: 4000000/12000000, 288433/IOPS
2019/07/28 12:22:22  - Completed/Total: 5000000/12000000, 301932/IOPS
2019/07/28 12:22:25  - Completed/Total: 6000000/12000000, 304692/IOPS
2019/07/28 12:22:28  - Completed/Total: 7000000/12000000, 287604/IOPS
2019/07/28 12:22:32  - Completed/Total: 8000000/12000000, 302297/IOPS
2019/07/28 12:22:35  - Completed/Total: 9000000/12000000, 302480/IOPS
2019/07/28 12:22:39  - Completed/Total: 10000000/12000000, 286450/IOPS
2019/07/28 12:22:42  - Completed/Total: 11000000/12000000, 302755/IOPS
2019/07/28 12:22:45 rpc.Serve: accept:server stopped
2019/07/28 12:22:46 average IOPS 293943
2019/07/28 12:22:46 total reads 12113400, total writes 0
2019/07/28 12:22:46 read latency sample count 121000
2019/07/28 12:22:46 write latency sample count 0
2019/07/28 12:22:46 read p999 2749μs p99 2552μs p95 2400μs avg 2006μs medium 2007μs
```

when ping time between two nodes are 0.1ms, I got 415,000 reads per second and the avg delay is 1.4ms. 

```
2019/07/28 12:24:06  - Completed/Total: 1000000/12000000, 356760/IOPS
2019/07/28 12:24:08  - Completed/Total: 2000000/12000000, 431965/IOPS
2019/07/28 12:24:10  - Completed/Total: 3000000/12000000, 425894/IOPS, latency: 1405 μs
2019/07/28 12:24:13  - Completed/Total: 4000000/12000000, 394321/IOPS
2019/07/28 12:24:15  - Completed/Total: 5000000/12000000, 434593/IOPS
2019/07/28 12:24:18  - Completed/Total: 6000000/12000000, 430848/IOPS, latency: 1443 μs
2019/07/28 12:24:20  - Completed/Total: 7000000/12000000, 396510/IOPS
2019/07/28 12:24:22  - Completed/Total: 8000000/12000000, 432713/IOPS
2019/07/28 12:24:25  - Completed/Total: 9000000/12000000, 434782/IOPS, latency: 1430 μs
2019/07/28 12:24:27  - Completed/Total: 10000000/12000000, 402576/IOPS
2019/07/28 12:24:30  - Completed/Total: 11000000/12000000, 432713/IOPS
2019/07/28 12:24:32 rpc.Serve: accept:server stopped
2019/07/28 12:24:32  - Completed/Total: 12000000/12000000, 438596/IOPS, latency: 1379 μs
2019/07/28 12:24:32 average IOPS 415000
2019/07/28 12:24:32 total reads 12114600, total writes 0
2019/07/28 12:24:32 read latency sample count 122600
2019/07/28 12:24:32 write latency sample count 0
2019/07/28 12:24:32 read p999 2168μs p99 1953μs p95 1800μs avg 1414μs medium 1411μs
```

Please also note that such "benchmark" is totally meaningless as - 
* CPU load is extremely low in such tests
* it is testing the throughput of a multi group raft library using a single Raft cluster

**Comment by 50829637** [comment]
c++代码：
get 请求过来先调用了： `rs = g_nh->ReadIndex(ullClusterID, timeout, p_pcsMyAsyncEvent);`，
然后 dragonboat::Event 类的set 函数中， 调用：`rs = g_nh->ReadLocal(ullClusterID, query, ret_buf);`

**Comment by lni** [comment]
@50829637 

I've updated the title to state that your reported issue happened when using the C++ wrapper. 
 
You may want to have a look at the example below. Note that libcppcoro is not strictly required, you get much higher throughput when your threads used for calling calling ReadIndex/ReadLocal are created by the Go runtime. See CRunIOServiceInGo() and its C++ binding RunIOServiceInGoRuntime() for more details.  

https://github.com/lni/cppasync
