### ISSUE TITLE
raft#restoreRemotes makes raft node blindly become follower

### ISSUE THREAD

**Issue by abbccdda** [lni/dragonboat#94]
This code logic in internal/raft.go:
```
func (r *raft) restoreRemotes(ss pb.Snapshot) {
  r.remotes = make(map[uint64]*remote)
  for id := range ss.Membership.Addresses {
    _, ok := r.observers[id]
    if ok {
       r.becomeFollower(r.term, r.leaderID)
   }
```
accidentally set raft node itself to follower. The original purpose was to make local observer remotes become followers during remote snapshot restoration, if the snapshot indicates it as a normal member.
As @lni discovered, the potential impact of this bug is that for 2 observers `x` and `y`, where `x` is fully caught up but `y` lags behind, snapshot will indicate `x` as a qualified member but when `y` receives the snapshot, it changes itself to follower role which is illegal, and potentially could start voting and election.

**Comment by lni** [comment]
Thanks @abbccdda for reporting this issue.
