### ISSUE TITLE
OnDisk Update() can improve performance like this?

### ISSUE THREAD

**Issue by xkeyideal** [lni/dragonboat#98]
```go   
        appliedIndex, err := d.queryAppliedIndex()
	if err != nil {
		return nil, err
	}

	firstIndex := ents[0].Index

	if appliedIndex+1-firstIndex < uint64(len(ents)) {
		ents = ents[appliedIndex+1-firstIndex:]
	}
```

if the raft node `ents[firstIndex].Index < appliedIndex < ents[lastIndex].Index`, can do above codes?

**Comment by xkeyideal** [comment]
`When there is any connectivity error between the local node and the remote
node, an ErrSnapshotStreaming will be returned by io.Writer's Write method
 when trying to write data to it. The SaveSnapshot method should return
 ErrSnapshotStreaming to terminate early.`

In SaveSnapshot function how to handle the `ErrSnapshotStreaming`, can give an example?

**Comment by lni** [comment]
@xkeyideal it is all up to you how you want to optimize the Update() method in your state machine. the most important thing here is that your Update() method must apply all entries supplied to it and correctly record the index of the last applied entry.

In Update(), your code normally doesn't need to query what is the last applied index as all entries supplied to Update() will be the ones that have not been applied yet. 

Note that it is also your responsibility to correctly fsync all on disk data when Sync() is called.

**Comment by xkeyideal** [comment]
got it, thx
